ValueSet: MII_VS_Mikrobio_Mikroskopie_Tests_LOINC
Id: mii-vs-mikrobio-mikroskopie-tests-loinc
Title: "MII VS Mikrobio Mikroskopie Tests [LOINC]"
* ^url = "https://www.medizininformatik-initiative.de/fhir/modul-mikrobiologie/ValueSet/mii-vs-mikrobio-mikroskopie-tests-loinc"
* ^status = #active
* ^version = "2025.0.0"
* ^contact.telecom.system = #email
* LOINC#10680-7 "Herpes simplex virus identified in Cerebral spinal fluid by Electron microscopy"
* LOINC#10681-5 "Herpes simplex virus identified in Tissue by Electron microscopy"
* LOINC#10649-2 "Calicivirus [Identifier] in Stool by Electron microscopy"
* LOINC#76699-8 "Filaria identified in Skin by Light microscopy"
* LOINC#10658-3 "Cyanobacterium identified in Water by Light microscopy"
* LOINC#10646-8 "Astrovirus [Identifier] in Stool by Electron microscopy"
* LOINC#10347-3 "Babesia microti identified in Blood by Light microscopy"
* LOINC#52107-0 "Bacterial capsule [Identifier] in Specimen by Light microscopy"
* LOINC#13325-6 "Bartonella sp identified in Blood by Light microscopy"
* LOINC#10661-7 "Dinoflagellate identified in Water by Light microscopy"
* LOINC#88156-5 "Microscopic observation [Identifier] in Amniotic fluid by Acid fast stain"
* LOINC#87970-0 "Microscopic observation [Identifier] in Amniotic fluid by Giemsa stain"
* LOINC#87971-8 "Microscopic observation [Identifier] in Amniotic fluid by Gram stain"
* LOINC#72408-8 "Microscopic observation [Identifier] in Anal by Gram stain"
* LOINC#88159-9 "Microscopic observation [Identifier] in Aspirate by Acid fast stain"
* LOINC#88684-6 "Microscopic observation [Identifier] in Aspirate by Giemsa stain"
* LOINC#14358-6 "Microscopic observation [Identifier] in Aspirate by Gram stain"
* LOINC#55222-4 "Microscopic observation [Identifier] in Aspirate by Rhodamine-auramine fluorochrome stain"
* LOINC#76082-7 "Microscopic observation [Identifier] in Bronchoalveolar lavage by Methenamine silver nitrate stain"
* LOINC#88231-6 "Microscopic observation [Identifier] in Bile fluid by Acid fast stain"
* LOINC#90261-9 "Microscopic observation [Identifier] in Bile fluid by Giemsa stain"
* LOINC#90262-7 "Microscopic observation [Identifier] in Bile fluid by Gram stain"
* LOINC#32699-1 "Microscopic observation [Identifier] in Blood by Acid fast stain"
* LOINC#29776-2 "Microscopic observation [Identifier] in Blood by Brilliant cresyl blue"
* LOINC#87969-2 "Microscopic observation [Identifier] in Blood by Gram stain"
* LOINC#73694-2 "Microscopic observation [Identifier] in Blood by KOH preparation"
* LOINC#32700-7 "Microscopic observation [Identifier] in Blood by Malaria smear"
* LOINC#33271-8 "Microscopic observation [Identifier] in Blood by Malaria thin smear"
* LOINC#33270-0 "Microscopic observation [Identifier] in Buffy Coat by Light microscopy"
* LOINC#9786-5 "Microscopic observation [Identifier] in Blood or Marrow by Periodic acid-Schiff stain"
* LOINC#32189-3 "Microscopic observation [Identifier] in Body fluid by Acid fast stain"
* LOINC#58944-0 "Microscopic observation [Identifier] in Body fluid by Acid fast stain.Ziehl-Neelsen"
* LOINC#48722-3 "Microscopic observation [Identifier] in Body fluid by Crystal violet stain"
* LOINC#87968-4 "Microscopic observation [Identifier] in Body fluid by Giemsa stain"
* LOINC#27112-2 "Microscopic observation [Identifier] in Body fluid by Gram stain"
* LOINC#68383-9 "Microscopic observation [Identifier] in Body fluid by KOH preparation"
* LOINC#53912-2 "Microscopic observation [Identifier] in Body fluid by Rhodamine-auramine fluorochrome stain"
* LOINC#23901-2 "Microscopic observation [Identifier] in Body fluid by Wet preparation"
* LOINC#88153-2 "Microscopic observation [Identifier] in Bone marrow by Acid fast stain"
* LOINC#87966-8 "Microscopic observation [Identifier] in Bone marrow by Giemsa stain"
* LOINC#87967-6 "Microscopic observation [Identifier] in Bone marrow by Gram stain"
* LOINC#53918-9 "Microscopic observation [Identifier] in Bone marrow by Rhodamine-auramine fluorochrome stain"
* LOINC#10355-6 "Microscopic observation [Identifier] in Bone marrow by Wright Giemsa stain"
* LOINC#24002-8 "Microscopic observation [Identifier] in Bronchial specimen by Acid fast stain"
* LOINC#21021-1 "Microscopic observation [Identifier] in Bronchial specimen by Gram stain"
* LOINC#32811-2 "Microscopic observation [Identifier] in Bronchial specimen by Iron hematoxylin stain"
* LOINC#53522-9 "Microscopic observation [Identifier] in Bronchial specimen by Rhodamine-auramine fluorochrome stain"
* LOINC#87974-2 "Microscopic observation [Identifier] in Burn by Gram stain"
* LOINC#87999-9 "Microscopic observation [Identifier] in Contact lens by Gram stain"
* LOINC#88170-6 "Microscopic observation [Identifier] in Cornea or Conjunctiva by Gram stain"
* LOINC#32190-1 "Microscopic observation [Identifier] in Cerebral spinal fluid"
* LOINC#32188-5 "Microscopic observation [Identifier] in Cerebral spinal fluid by Acid fast stain"
* LOINC#58943-2 "Microscopic observation [Identifier] in Cerebral spinal fluid by Acid fast stain.Ziehl-Neelsen"
* LOINC#59474-7 "Microscopic observation [Identifier] in Cerebral spinal fluid by Acridine orange stain"
* LOINC#87965-0 "Microscopic observation [Identifier] in Cerebral spinal fluid by Giemsa stain"
* LOINC#14357-8 "Microscopic observation [Identifier] in Cerebral spinal fluid by Gram stain"
* LOINC#638-7 "Microscopic observation [Identifier] in Cerebral spinal fluid by India ink prep"
* LOINC#53906-4 "Microscopic observation [Identifier] in Cerebral spinal fluid by Rhodamine-auramine fluorochrome stain"
* LOINC#90282-5 "Microscopic observation [Identifier] in Catheter tip by Gram stain"
* LOINC#89582-1 "Microscopic observation [Identifier] in Cervix by Acid fast stain"
* LOINC#88152-4 "Microscopic observation [Identifier] in Cervix by Acid fast stain.Kinyoun"
* LOINC#6464-2 "Microscopic observation [Identifier] in Cervix by Gram stain"
* LOINC#14355-2 "Microscopic observation [Identifier] in Cervix by KOH preparation"
* LOINC#14318-0 "Microscopic observation [Identifier] in Cervix by Wet preparation"
* LOINC#18326-9 "Microscopic observation [Identifier] in Cervix by Other stain"
* LOINC#21022-9 "Microscopic observation [Identifier] in Dialysis fluid by Gram stain"
* LOINC#88001-3 "Microscopic observation [Identifier] in Peritoneal dialysis fluid by Gram stain"
* LOINC#6465-9 "Microscopic observation [Identifier] in Duodenal fluid by Trichrome stain"
* LOINC#6466-7 "Microscopic observation [Identifier] in Duodenal fluid by Wet preparation"
* LOINC#18327-7 "Microscopic observation [Identifier] in Duodenal fluid by Other stain"
* LOINC#14365-1 "Microscopic observation [Identifier] in Ear by Gram stain"
* LOINC#53914-8 "Microscopic observation [Identifier] in Endometrium by Rhodamine-auramine fluorochrome stain"
* LOINC#14364-4 "Microscopic observation [Identifier] in Eye by Gram stain"
* LOINC#11476-9 "Microscopic observation [Identifier] in Gastric fluid by Acid fast stain"
* LOINC#640-3 "Microscopic observation [Identifier] in Gastric fluid by Acid fast stain.Kinyoun"
* LOINC#641-1 "Microscopic observation [Identifier] in Gastric fluid by Acid fast stain.Kinyoun modified"
* LOINC#642-9 "Microscopic observation [Identifier] in Gastric fluid by Acid fast stain.Ziehl-Neelsen"
* LOINC#20885-0 "Microscopic observation [Identifier] in Gastric fluid by Dark field examination"
* LOINC#53916-3 "Microscopic observation [Identifier] in Gastric fluid by Rhodamine-auramine fluorochrome stain"
* LOINC#88148-2 "Microscopic observation [Identifier] in Genital specimen by Acid fast stain"
* LOINC#91850-8 "Microscopic observation [Identifier] in Genital specimen by Giemsa stain"
* LOINC#48712-4 "Microscopic observation [Identifier] in Genital specimen by Gram stain"
* LOINC#14317-2 "Microscopic observation [Identifier] in Genital specimen by Wet preparation"
* LOINC#6467-5 "Microscopic observation [Identifier] in Genital fluid by Gram stain"
* LOINC#10856-3 "Microscopic observation [Identifier] in Genital mucus by Gram stain"
* LOINC#10688-0 "Microscopic observation [Identifier] in Hair by KOH preparation"
* LOINC#89660-5 "Microscopic observation [Identifier] in Implanted device by Acid fast stain"
* LOINC#89659-7 "Microscopic observation [Identifier] in Implanted device by Gram stain"
* LOINC#87975-9 "Microscopic observation [Identifier] in Isolate by Gram stain"
* LOINC#90269-2 "Microscopic observation [Identifier] in Milk by Acid fast stain"
* LOINC#90263-5 "Microscopic observation [Identifier] in Milk by Gram stain"
* LOINC#10689-8 "Microscopic observation [Identifier] in Nail by KOH preparation"
* LOINC#32026-7 "Microscopic observation [Identifier] in Nose by Gram stain"
* LOINC#88149-0 "Microscopic observation [Identifier] in Nasopharynx by Gram stain"
* LOINC#88155-7 "Microscopic observation [Identifier] in Ocular fluid by Acid fast stain"
* LOINC#88150-8 "Microscopic observation [Identifier] in Ocular fluid by Giemsa stain"
* LOINC#88158-1 "Microscopic observation [Identifier] in Ocular fluid by Gram stain"
* LOINC#32186-9 "Microscopic observation [Identifier] in Penis by Tzanck smear"
* LOINC#88145-8 "Microscopic observation [Identifier] in Pericardial fluid by Acid fast stain"
* LOINC#90267-6 "Microscopic observation [Identifier] in Pericardial fluid by Giemsa stain"
* LOINC#88147-4 "Microscopic observation [Identifier] in Pericardial fluid by Gram stain"
* LOINC#53915-5 "Microscopic observation [Identifier] in Pericardial fluid by Rhodamine-auramine fluorochrome stain"
* LOINC#88144-1 "Microscopic observation [Identifier] in Peritoneal fluid by Acid fast stain"
* LOINC#58945-7 "Microscopic observation [Identifier] in Peritoneal fluid by Acid fast stain.Ziehl-Neelsen"
* LOINC#90268-4 "Microscopic observation [Identifier] in Peritoneal fluid by Giemsa stain"
* LOINC#14359-4 "Microscopic observation [Identifier] in Peritoneal fluid by Gram stain"
* LOINC#53910-6 "Microscopic observation [Identifier] in Peritoneal fluid by Rhodamine-auramine fluorochrome stain"
* LOINC#88146-6 "Microscopic observation [Identifier] in Placenta by Gram stain"
* LOINC#14353-7 "Microscopic observation [Identifier] in Pleural fluid by Acid fast stain.Kinyoun modified"
* LOINC#58942-4 "Microscopic observation [Identifier] in Pleural fluid by Acid fast stain.Ziehl-Neelsen"
* LOINC#88000-5 "Microscopic observation [Identifier] in Pleural fluid by Giemsa stain"
* LOINC#14360-2 "Microscopic observation [Identifier] in Pleural fluid by Gram stain"
* LOINC#53907-2 "Microscopic observation [Identifier] in Pleural fluid by Rhodamine-auramine fluorochrome stain"
* LOINC#643-7 "Microscopic observation [Identifier] in Pus by Gram stain"
* LOINC#89662-1 "Microscopic observation [Identifier] in Lower respiratory specimen by Acid fast stain"
* LOINC#88633-3 "Microscopic observation [Identifier] in Lower respiratory specimen by Giemsa stain"
* LOINC#88632-5 "Microscopic observation [Identifier] in Lower respiratory specimen by Gram stain"
* LOINC#88685-3 "Microscopic observation [Identifier] in Lower respiratory specimen by KOH preparation"
* LOINC#89658-9 "Microscopic observation [Identifier] in Lower respiratory specimen by Methenamine silver nitrate stain"
* LOINC#89657-1 "Microscopic observation [Identifier] in Lower respiratory specimen by Toluidine blue O stain"
* LOINC#89661-3 "Microscopic observation [Identifier] in Upper respiratory specimen by Acid fast stain"
* LOINC#91808-6 "Microscopic observation [Identifier] in Upper respiratory specimen by Gram stain"
* LOINC#88634-1 "Microscopic observation [Identifier] in Saliva (oral fluid) by Gram stain"
* LOINC#88157-3 "Microscopic observation [Identifier] in Semen by Acid fast stain"
* LOINC#87973-4 "Microscopic observation [Identifier] in Semen by Gram stain"
* LOINC#88154-0 "Microscopic observation [Identifier] in Sinus by Acid fast stain"
* LOINC#87972-6 "Microscopic observation [Identifier] in Sinus by Gram stain"
* LOINC#94543-6 "Microscopic observation [Identifier] in Skin by Acid fast stain"
* LOINC#90296-5 "Microscopic observation [Identifier] in Skin by Gram stain"
* LOINC#644-5 "Microscopic observation [Identifier] in Skin by KOH preparation"
* LOINC#32187-7 "Microscopic observation [Identifier] in Skin by Tzanck smear"
* LOINC#11477-7 "Microscopic observation [Identifier] in Sputum by Acid fast stain"
* LOINC#645-2 "Microscopic observation [Identifier] in Sputum by Acid fast stain.Kinyoun"
* LOINC#646-0 "Microscopic observation [Identifier] in Sputum by Acid fast stain.Kinyoun modified"
* LOINC#647-8 "Microscopic observation [Identifier] in Sputum by Acid fast stain.Ziehl-Neelsen"
* LOINC#6468-3 "Microscopic observation [Identifier] in Sputum by Calcofluor white"
* LOINC#648-6 "Microscopic observation [Identifier] in Sputum by Gram stain"
* LOINC#17281-7 "Microscopic observation [Identifier] in Sputum by KOH preparation"
* LOINC#53904-9 "Microscopic observation [Identifier] in Sputum by Rhodamine-auramine fluorochrome stain"
* LOINC#11478-5 "Microscopic observation [Identifier] in Stool by Acid fast stain"
* LOINC#20884-3 "Microscopic observation [Identifier] in Stool by Dark field examination"
* LOINC#649-4 "Microscopic observation [Identifier] in Stool by Gram stain"
* LOINC#8250-3 "Microscopic observation [Identifier] in Stool by Electron microscopy"
* LOINC#20882-7 "Microscopic observation [Identifier] in Stool by Electron microscopy negative stain"
* LOINC#6469-1 "Microscopic observation [Identifier] in Stool by Trichrome stain"
* LOINC#6470-9 "Microscopic observation [Identifier] in Stool by Wet preparation"
* LOINC#63433-7 "Microscopic observation [Identifier] in Synovial fluid by Acid fast stain.Ziehl-Neelsen"
* LOINC#88235-7 "Microscopic observation [Identifier] in Synovial fluid by Giemsa stain"
* LOINC#14363-6 "Microscopic observation [Identifier] in Synovial fluid by Gram stain"
* LOINC#53913-0 "Microscopic observation [Identifier] in Synovial fluid by Rhodamine-auramine fluorochrome stain"
* LOINC#75222-0 "Microscopic observation [Identifier] in Throat by Alberts stain"
* LOINC#14362-8 "Microscopic observation [Identifier] in Throat by Gram stain"
* LOINC#11479-3 "Microscopic observation [Identifier] in Tissue by Acid fast stain"
* LOINC#6655-5 "Microscopic observation [Identifier] in Tissue by Acid fast stain.Kinyoun"
* LOINC#6656-3 "Microscopic observation [Identifier] in Tissue by Acid fast stain.Kinyoun modified"
* LOINC#6657-1 "Microscopic observation [Identifier] in Tissue by Acid fast stain.Ziehl-Neelsen"
* LOINC#6658-9 "Microscopic observation [Identifier] in Tissue by Acridine orange stain"
* LOINC#6472-5 "Microscopic observation [Identifier] in Tissue by Calcofluor white"
* LOINC#6659-7 "Microscopic observation [Identifier] in Tissue by Carbol-fuchsin stain"
* LOINC#6607-6 "Microscopic observation [Identifier] in Tissue by Dark field examination"
* LOINC#6661-3 "Microscopic observation [Identifier] in Tissue by Dry mount"
* LOINC#6662-1 "Microscopic observation [Identifier] in Tissue by Giemsa stain"
* LOINC#6663-9 "Microscopic observation [Identifier] in Tissue by Gimenez stain"
* LOINC#6664-7 "Microscopic observation [Identifier] in Tissue by Gram stain"
* LOINC#6665-4 "Microscopic observation [Identifier] in Tissue by Hematoxylin and eosin stain"
* LOINC#6666-2 "Microscopic observation [Identifier] in Tissue by India ink prep"
* LOINC#6667-0 "Microscopic observation [Identifier] in Tissue by KOH preparation"
* LOINC#6669-6 "Microscopic observation [Identifier] in Tissue by Macchiavello stain"
* LOINC#6670-4 "Microscopic observation [Identifier] in Tissue by Malaria smear"
* LOINC#6671-2 "Microscopic observation [Identifier] in Tissue by Methenamine silver nitrate stain"
* LOINC#6672-0 "Microscopic observation [Identifier] in Tissue by Methylene blue stain.Loeffler"
* LOINC#6668-8 "Microscopic observation [Identifier] in Tissue by M'Fadyean stain"
* LOINC#20881-9 "Microscopic observation [Identifier] in Tissue by Electron microscopy thin sectiion"
* LOINC#6673-8 "Microscopic observation [Identifier] in Tissue by Neisser stain"
* LOINC#10637-7 "Microscopic observation [Identifier] in Tissue by Night blue stain"
* LOINC#6675-3 "Microscopic observation [Identifier] in Tissue by Periodic acid-Schiff stain"
* LOINC#6677-9 "Microscopic observation [Identifier] in Tissue by Rhodamine-auramine fluorochrome stain"
* LOINC#6473-3 "Microscopic observation [Identifier] in Tissue by Trichrome stain"
* LOINC#6679-5 "Microscopic observation [Identifier] in Tissue by Warthin-Starry stain"
* LOINC#6680-3 "Microscopic observation [Identifier] in Tissue by Wet preparation"
* LOINC#6681-1 "Microscopic observation [Identifier] in Tissue by Wright stain"
* LOINC#6471-7 "Microscopic observation [Identifier] in Tissue by Other stain"
* LOINC#6474-1 "Microscopic observation [Identifier] in Urethra by Gram stain"
* LOINC#57851-8 "Microscopic observation [Identifier] in Urethra by Wet preparation"
* LOINC#11480-1 "Microscopic observation [Identifier] in Urine by Acid fast stain"
* LOINC#650-2 "Microscopic observation [Identifier] in Urine by Acid fast stain.Kinyoun"
* LOINC#651-0 "Microscopic observation [Identifier] in Urine by Acid fast stain.Kinyoun modified"
* LOINC#652-8 "Microscopic observation [Identifier] in Urine by Acid fast stain.Ziehl-Neelsen"
* LOINC#20883-5 "Microscopic observation [Identifier] in Urine by Dark field examination"
* LOINC#653-6 "Microscopic observation [Identifier] in Urine by Gram stain"
* LOINC#68958-8 "Microscopic observation [Identifier] in Urine by KOH preparation"
* LOINC#53905-6 "Microscopic observation [Identifier] in Urine by Rhodamine-auramine fluorochrome stain"
* LOINC#14361-0 "Microscopic observation [Identifier] in Vaginal fluid by Gram stain"
* LOINC#14356-0 "Microscopic observation [Identifier] in Vaginal fluid by KOH preparation"
* LOINC#14319-8 "Microscopic observation [Identifier] in Vaginal fluid by Wet preparation"
* LOINC#88635-8 "Microscopic observation [Identifier] in Vomitus by Gram stain"
* LOINC#88151-6 "Microscopic observation [Identifier] in Wound by Acid fast stain"
* LOINC#14354-5 "Microscopic observation [Identifier] in Wound by Acid fast stain.Kinyoun modified"
* LOINC#10357-2 "Microscopic observation [Identifier] in Wound by Gram stain"
* LOINC#11545-1 "Microscopic observation [Identifier] in Specimen by Acid fast stain"
* LOINC#654-4 "Microscopic observation [Identifier] in Specimen by Acid fast stain.Kinyoun"
* LOINC#655-1 "Microscopic observation [Identifier] in Specimen by Acid fast stain.Kinyoun modified"
* LOINC#656-9 "Microscopic observation [Identifier] in Specimen by Acid fast stain.Ziehl-Neelsen"
* LOINC#657-7 "Microscopic observation [Identifier] in Specimen by Acridine orange stain"
* LOINC#658-5 "Microscopic observation [Identifier] in Specimen by Calcofluor white"
* LOINC#659-3 "Microscopic observation [Identifier] in Specimen by Carbol-fuchsin stain"
* LOINC#660-1 "Microscopic observation [Identifier] in Specimen by Dark field examination"
* LOINC#661-9 "Microscopic observation [Identifier] in Specimen by Dry mount"
* LOINC#662-7 "Microscopic observation [Identifier] in Specimen by Giemsa stain"
* LOINC#663-5 "Microscopic observation [Identifier] in Specimen by Gimenez stain"
* LOINC#664-3 "Microscopic observation [Identifier] in Specimen by Gram stain"
* LOINC#665-0 "Microscopic observation [Identifier] in Specimen by Hematoxylin and eosin stain"
* LOINC#35347-4 "Microscopic observation [Identifier] in Specimen by Immunofluorescence"
* LOINC#666-8 "Microscopic observation [Identifier] in Specimen by India ink prep"
* LOINC#14841-1 "Microscopic observation [Identifier] in Specimen by Iron hematoxylin stain"
* LOINC#14842-9 "Microscopic observation [Identifier] in Specimen by Kinyoun iron hematoxylin stain"
* LOINC#667-6 "Microscopic observation [Identifier] in Specimen by KOH preparation"
* LOINC#51700-3 "Microscopic observation [Identifier] in Specimen by Lactophenol blue"
* LOINC#669-2 "Microscopic observation [Identifier] in Specimen by Macchiavello stain"
* LOINC#33699-0 "Microscopic observation [Identifier] in Specimen by Malachite green stain"
* LOINC#670-0 "Microscopic observation [Identifier] in Specimen by Methenamine silver nitrate stain"
* LOINC#671-8 "Microscopic observation [Identifier] in Specimen by Methylene blue stain.Loeffler"
* LOINC#668-4 "Microscopic observation [Identifier] in Specimen by M'Fadyean stain"
* LOINC#34166-9 "Microscopic observation [Identifier] in Specimen by Electron microscopy"
* LOINC#672-6 "Microscopic observation [Identifier] in Specimen by Neisser stain"
* LOINC#674-2 "Microscopic observation [Identifier] in Specimen by Periodic acid-Schiff stain"
* LOINC#676-7 "Microscopic observation [Identifier] in Specimen by Rhodamine-auramine fluorochrome stain"
* LOINC#20431-3 "Microscopic observation [Identifier] in Specimen by Smear"
* LOINC#677-5 "Microscopic observation [Identifier] in Specimen by Toluidine blue O stain"
* LOINC#678-3 "Microscopic observation [Identifier] in Specimen by Trichrome stain"
* LOINC#45043-7 "Microscopic observation [Identifier] in Specimen by Tzanck smear"
* LOINC#679-1 "Microscopic observation [Identifier] in Specimen by Warthin-Starry stain"
* LOINC#44098-2 "Microscopic observation [Identifier] in Specimen by Wayson stain"
* LOINC#680-9 "Microscopic observation [Identifier] in Specimen by Wet preparation"
* LOINC#682-5 "Microscopic observation [Identifier] in Specimen by Wright Giemsa stain"
* LOINC#681-7 "Microscopic observation [Identifier] in Specimen by Wright stain"
* LOINC#11546-9 "Microscopic observation [Identifier] in Specimen by Other stain"
* LOINC#79375-2 "Microscopic observation [Identifier] in Sputum by Acid fast stain.Ziehl-Neelsen--2nd specimen"
* LOINC#79376-0 "Microscopic observation [Identifier] in Sputum by Acid fast stain.Ziehl-Neelsen--3rd specimen"
* LOINC#10857-1 "Microsporidia identified in Specimen by Light microscopy"
* LOINC#88337-1 "Mite identified in Ear by Light microscopy"
* LOINC#10692-2 "Mushroom.toxic identified in Food by Light microscopy"
* LOINC#10693-0 "Mushroom.toxic identified in Vomitus by Light microscopy"
* LOINC#10696-3 "Norovirus [Identifier] in Stool by Electron microscopy"
* LOINC#10700-3 "Orthopoxvirus [Identifier] in Skin by Electron microscopy"
* LOINC#10855-5 "Ova and parasites identified in Duodenal fluid or Gastric fluid by Light microscopy"
* LOINC#91826-8 "Ova and parasites identified in Lower respiratory specimen by Light microscopy"
* LOINC#91768-2 "Ova and parasites identified in Sputum by Light microscopy"
* LOINC#10704-5 "Ova and parasites identified in Stool by Light microscopy"
* LOINC#6674-6 "Ova and parasites identified in Tissue by Light microscopy"
* LOINC#673-4 "Ova and parasites identified in Specimen by Light microscopy"
* LOINC#13319-9 "Ova and parasites identified in Stool by Light microscopy--2nd specimen"
* LOINC#52795-2 "Ova and parasites identified in Specimen by Light microscopy--2nd specimen"
* LOINC#13320-7 "Ova and parasites identified in Stool by Light microscopy--3rd specimen"
* LOINC#52794-5 "Ova and parasites identified in Specimen by Light microscopy--3rd specimen"
* LOINC#17784-0 "Parasite identified in Blood by Light microscopy"
* LOINC#53609-4 "Parasite identified in Bone marrow by Light microscopy"
* LOINC#98026-8 "Parasite identified in Prostatic fluid by Light microscopy"
* LOINC#20933-8 "Parasite identified in Serum by Light microscopy"
* LOINC#10706-0 "Picornavirus [Identifier] in Stool by Electron microscopy"
* LOINC#10708-6 "Toxic Plant identified in Vomitus by Light microscopy"
* LOINC#32206-5 "Plasmodium sp identified in Blood by Light microscopy"
* LOINC#41451-6 "Plasmodium stage [Identifier] in Blood by Light microscopy"
* LOINC#13326-4 "Pneumocystis sp identified in Specimen by Light microscopy"
* LOINC#9787-3 "Sarcoptes scabiei identified in Skin by Light microscopy"
* LOINC#76767-3 "Schistosoma sp identified in Semen by Light microscopy"
* LOINC#10715-1 "Schistosoma sp identified in Urine sediment by Light microscopy"
* LOINC#10722-7 "Torovirus [Identifier] in Stool by Electron microscopy"
* LOINC#74037-3 "Transmissible spongiform encephalopathy [Identifier] in Brain by Light microscopy"
* LOINC#10729-2 "Trypanosoma sp identified in Blood by Light microscopy"
* LOINC#14839-5 "Trypanosoma sp identified in Buffy Coat by Light microscopy"
* LOINC#10734-2 "Varicella zoster virus identified in Skin by Electron microscopy"
* LOINC#10736-7 "Virus identified in Cerebral spinal fluid by Electron microscopy"
* LOINC#10737-5 "Virus identified in Stool by Electron microscopy"
* LOINC#10738-3 "Virus identified in Tissue by Electron microscopy"
* LOINC#10739-1 "Virus identified in Specimen by Electron microscopy"
* LOINC#24421-0 "Haemobartonella felis [Presence] in Blood by Light microscopy"
* LOINC#22971-6 "Caprine arthritis encephalitis virus [Presence] in Specimen by Electron microscopy"
* LOINC#88344-7 "Intracellular bacteria [Presence] in Ear by Light microscopy"
* LOINC#32158-8 "Klebsiella granulomatis [Presence] in Genital specimen by Light microscopy"
* LOINC#43400-1 "Lactobacillus sp morphotypes [Presence] in Vaginal fluid by Light microscopy"
* LOINC#23212-4 "Lumpy skin disease virus [Presence] in Tissue by Electron microscopy"
* LOINC#48982-3 "Ehrlichia sp [Presence] in Specimen by Light microscopy"
* LOINC#88338-9 "Coccal bacteria [Presence] in Ear by Light microscopy"
* LOINC#23016-9 "Coxiella burnetii [Presence] in Placenta by Light microscopy"
* LOINC#44275-6 "Coxiella burnetii [Presence] in Specimen by Light microscopy"
* LOINC#16719-7 "Cytomegalovirus inclusion bodies [Presence] in Urine by Microscopic observation"
* LOINC#7809-7 "Astrovirus [Presence] in Stool by Electron microscopy"
* LOINC#22811-4 "Avian infectious laryngotracheitis virus [Presence] in Specimen by Electron microscopy"
* LOINC#22836-1 "Avian pox virus [Presence] in Tissue by Electron microscopy"
* LOINC#88339-7 "Bacilliform bacteria [Presence] in Ear by Light microscopy"
* LOINC#96601-0 "Bacilliform bacteria [Presence] in Skin by Light microscopy"
* LOINC#95074-1 "Bacteria [Presence] in Bronchoalveolar lavage by Light microscopy"
* LOINC#41599-2 "Bacteria [Presence] in Body fluid by Light microscopy"
* LOINC#41602-4 "Bacteria [Presence] in Cerebral spinal fluid by Light microscopy"
* LOINC#44039-6 "Bacteria [Presence] in Eye by Light microscopy"
* LOINC#18192-5 "Bacteria [Presence] in Nose by Light microscopy"
* LOINC#41598-4 "Bacteria [Presence] in Pericardial fluid by Light microscopy"
* LOINC#41601-6 "Bacteria [Presence] in Peritoneal fluid by Light microscopy"
* LOINC#41603-2 "Bacteria [Presence] in Pleural fluid by Light microscopy"
* LOINC#41600-8 "Bacteria [Presence] in Synovial fluid by Light microscopy"
* LOINC#22993-0 "Chlamydophila psittaci [Presence] in Placenta by Electron microscopy"
* LOINC#22808-0 "Infectious bronchitis virus [Presence] in Specimen by Electron microscopy"
* LOINC#23381-7 "Abnormal Prion Protein [Presence] in Brain by Electron microscopy"
* LOINC#48981-5 "Anaplasma sp [Presence] in Specimen by Light microscopy"
* LOINC#88342-1 "Malassezia sp [Presence] in Ear by Light microscopy"
* LOINC#23573-9 "Rabbit hemorrhagic disease virus [Presence] in Tissue by Electron microscopy"
* LOINC#23388-2 "Rabies virus [Presence] in Brain by Light microscopy"
* LOINC#51783-9 "Reagin Ab [Presence] in Cord blood by VDRL"
* LOINC#5290-2 "Reagin Ab [Presence] in Cerebral spinal fluid by VDRL"
* LOINC#5292-8 "Reagin Ab [Presence] in Serum by VDRL"
* LOINC#21030-2 "Reagin Ab [Presence] in Serum from Donor by VDRL"
* LOINC#14904-7 "Reagin Ab [Presence] in Specimen by VDRL"
* LOINC#23030-0 "Duck enteritis virus [Presence] in Tissue by Electron microscopy"
* LOINC#43398-7 "Gardnerella vaginalis+Prevotella sp morphotypes [Presence] in Vaginal fluid by Light microscopy"
* LOINC#76083-5 "Microscopic observation [Presence] in Bronchoalveolar lavage by Acid fast stain.Ziehl-Neelsen"
* LOINC#88171-4 "Microscopic observation [Presence] in Cornea or Conjunctiva by Acid fast stain"
* LOINC#88172-2 "Microscopic observation [Presence] in Isolate by Acid fast stain"
* LOINC#88173-0 "Microscopic observation [Presence] in Pleural fluid by Acid fast stain"
* LOINC#88631-7 "Microscopic observation [Presence] in Lower respiratory specimen by Acid fast stain.Kinyoun"
* LOINC#88234-0 "Microscopic observation [Presence] in Synovial fluid by Acid fast stain"
* LOINC#88366-0 "Microscopic observation [Presence] in Vomitus by Acid fast stain"
* LOINC#72357-7 "Microscopic observation [Presence] in Specimen by Acid fast stain"
* LOINC#87243-2 "Microscopic observation [Presence] in Specimen by Auramine fluorochrome stain"
* LOINC#94856-2 "Microscopic observation [Presence] in Sputum by Acid fast stain --2nd specimen"
* LOINC#94857-0 "Microscopic observation [Presence] in Sputum by Acid fast stain --3rd specimen"
* LOINC#88340-5 "Mite [Presence] in Ear by Light microscopy"
* LOINC#7973-1 "Norovirus [Presence] in Stool by Electron microscopy"
* LOINC#91900-1 "Parasite [Presence] in Blood by Light microscopy"
* LOINC#51587-4 "Plasmodium sp [Presence] in Blood by Light microscopy"
* LOINC#20949-4 "Rickettsia sp [Presence] in Blood by Light microscopy"
* LOINC#8011-9 "Rotavirus [Presence] in Stool by Electron microscopy"
* LOINC#38275-4 "Transmissible spongiform encephalopathy [Presence] in Brain by Light microscopy"
* LOINC#23499-7 "Trichinella spiralis [Presence] in Tissue by Light microscopy"
* LOINC#91845-8 "Trichomonas vaginalis [Presence] in Genital specimen by Light microscopy"
* LOINC#72277-7 "Trichomonas vaginalis [Presence] in Prostatic fluid by Light microscopy"
* LOINC#90286-6 "Trichomonas vaginalis [Presence] in Vaginal fluid by Light microscopy"
* LOINC#41222-1 "Yeast [Presence] in Body fluid by Light microscopy"
* LOINC#41242-9 "Yeast [Presence] in Cerebral spinal fluid by Light microscopy"
* LOINC#80725-5 "Trichomonas sp [Presence] in Semen by Light microscopy"
* LOINC#32724-7 "Trichomonas sp [Presence] in Urine by Light microscopy"
* LOINC#90303-9 "Trichomonas vaginalis [Presence] in Cervix by Light microscopy"
* LOINC#23509-3 "Trypanosoma equiperdum [Presence] in Body fluid by Light microscopy"
* LOINC#17773-3 "Yeast [Presence] in Stool by Light microscopy"