ValueSet: MII_VS_Mikrobio_Virulenz_LOINC
Id: mii-vs-mikrobio-virulenz-loinc
Title: "MII VS Mikrobio Virulenz [LOINC]"
* ^status = #active
* ^version = "2025.0.0"
* ^date = "2023-03-02T00:00:00Z"
* LOINC#87402-4 "Escherichia coli aidA-I gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87318-2 "Escherichia coli eaeA gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87319-0 "Escherichia coli enteroaggregative astA gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87320-8 "Escherichia coli enterotoxigenic heat-labile toxin DNA [Presence] in Isolate by NAA with probe detection"
* LOINC#87321-6 "Escherichia coli enterotoxigenic sta gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87322-4 "Escherichia coli enterotoxigenic stb gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87370-3 "Escherichia coli fasA gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87371-1 "Escherichia coli fedF gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87372-9 "Escherichia coli FimF41a gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87373-7 "Escherichia coli K88 DNA [Presence] in Isolate by NAA with probe detection"
* LOINC#87374-5 "Escherichia coli K99 DNA [Presence] in Isolate by NAA with probe detection"
* LOINC#87375-2 "Escherichia coli paa gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87376-0 "Escherichia coli Stx1 toxin stx1 gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87377-8 "Escherichia coli Stx2 toxin stx2 gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87380-2 "Escherichia coli Stx2e-Toxin stx2e-Gen [Nachweis] in Isolat mittels Nukleinsäureamplifikation mit Sondendetektion"
* LOINC#87304-2 "Clostridium perfringens cpa gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87397-6 "Clostridium perfringens cpb gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87305-9 "Clostridium perfringens cpb2 gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87306-7 "Clostridium perfringens cpe gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87307-5 "Clostridium perfringens etx gene [Presence] in Isolate by NAA with probe detection"
* LOINC#87313-3 "Clostridium perfringens iota toxin DNA [Presence] in Isolate by NAA with probe detection"
* LOINC#44796-1 "Clostridium botulinum toxin [Identifier] in Specimen"
* LOINC#44274-9 "Clostridium botulinum toxin [Identifier] in Specimen by Immunoassay"
* LOINC#33764-2 "Shiga toxin stx gene [Identifier] in Specimen by NAA with probe detection"
* LOINC#20706-8 "Clostridium botulinum toxin [Identifier] in Specimen by Animal inoculation"
* LOINC#53946-0 "Escherichia coli shiga-like toxin identified in Specimen"
* LOINC#46706-8 "Clostridium perfringens toxin gene [Identifier] in Specimen by NAA with probe detection"
* LOINC#46705-0 "Clostridium botulinum toxin gene [Identifier] in Specimen by NAA with probe detection"
* LOINC#53941-1 "Vibrio cholerae toxin Ag [Presence] in Isolate"
* LOINC#24102-6 "Corynebacterium toxin [Presence] in Specimen by Immune diffusion (ID)"
* LOINC#13329-8 "Escherichia coli labile toxin [Presence] in Specimen"
* LOINC#33708-9 "Clostridium botulinum toxin [Presence] in Specimen"
* LOINC#33712-1 "Clostridium botulinum toxin A+B+E [Presence] in Specimen"
* LOINC#33696-6 "Clostridium botulinum toxin [Presence] in Specimen by Mouse bioassay"
* LOINC#33709-7 "Clostridium botulinum toxin A [Presence] in Specimen"
* LOINC#33713-9 "Clostridium botulinum toxin B [Presence] in Specimen"
* LOINC#33710-5 "Clostridium botulinum toxin E [Presence] in Specimen"
* LOINC#23349-4 "Pasteurella multocida toxin [Presence] in Specimen by Immunoassay"
* LOINC#45039-5 "Clostridium botulinum toxin [Presence] in Specimen by Immunoassay"
* LOINC#33711-3 "Clostridium botulinum toxin F [Presence] in Specimen"
* LOINC#33704-8 "Clostridium botulinum toxin A+B+E [Presence] in Specimen by Mouse bioassay neutralization"
* LOINC#33701-4 "Clostridium botulinum toxin A [Presence] in Specimen by Mouse bioassay neutralization"
* LOINC#33705-5 "Clostridium botulinum toxin B [Presence] in Specimen by Mouse bioassay neutralization"
* LOINC#33702-2 "Clostridium botulinum toxin E [Presence] in Specimen by Mouse bioassay neutralization"
* LOINC#38989-0 "Clostridium botulinum toxin A+B+E+F+G [Presence] in Specimen by Mouse bioassay neutralization"
* LOINC#63427-9 "Escherichia coli Stx1 toxin stx1 gene [Presence] in Specimen by NAA with probe detection"
* LOINC#63428-7 "Escherichia coli Stx2 toxin stx2 gene [Presence] in Specimen by NAA with probe detection"
* LOINC#71786-8 "Staphylococcus aureus exfoliative toxin A eta gene [Presence] in Specimen by NAA with probe detection"
* LOINC#71787-6 "Staphylococcus aureus exfoliative toxin B etb gene [Presence] in Specimen by NAA with probe detection"
* LOINC#41630-5 "Clostridium botulinum toxin A [Presence] in Specimen by Immunofluorescence"
* LOINC#41632-1 "Clostridium botulinum toxin B [Presence] in Specimen by Immunofluorescence"
* LOINC#41634-7 "Clostridium botulinum toxin E [Presence] in Specimen by Immunofluorescence"
* LOINC#41635-4 "Clostridium botulinum toxin F [Presence] in Specimen by Immunofluorescence"
* LOINC#33703-0 "Clostridium botulinum toxin F [Presence] in Specimen by Mouse bioassay neutralization"
* LOINC#23935-0 "Staphylococcus aureus toxic shock syndrome toxin 1 [Presence] in Specimen"
* LOINC#80518-4 "Clostridium baratii toxin F bont gene [Presence] in Specimen by NAA with probe detection"
* LOINC#81644-7 "Clostridium botulinum toxin C botC gene [Presence] in Specimen by NAA with probe detection"
* LOINC#81645-4 "Clostridium botulinum toxin D botD gene [Presence] in Specimen by NAA with probe detection"
* LOINC#81646-2 "Clostridium botulinum toxin E botE gene [Presence] in Specimen by NAA with probe detection"
* LOINC#81647-0 "Clostridium botulinum toxin F botF gene [Presence] in Specimen by NAA with probe detection"
* LOINC#53943-7 "Bacterial cytolethal distending toxin cdt gene [Presence] in Specimen by NAA with probe detection"
* LOINC#53947-8 "Escherichia coli Stx1 and Stx2 toxin stx1 and stx2 and H7 flagellar fliC genes [Identifier] in Specimen by NAA with probe detection"
* LOINC#94611-1 "Pasteurella multocida toxin toxA gene [Presence] in Specimen by NAA with probe detection"
* LOINC#41631-3 "Clostridium botulinum toxin A botA gene [Presence] in Specimen by NAA with probe detection"
* LOINC#41633-9 "Clostridium botulinum toxin B botB gene [Presence] in Specimen by NAA with probe detection"
* LOINC#81648-8 "Clostridium botulinum toxin G botG gene [Presence] in Specimen by NAA with probe detection"
* LOINC#44881-1 "Staphylococcus aureus toxic shock syndrome toxin gene [Presence] in Specimen by NAA with probe detection"
* LOINC#53942-9 "Vibrio cholerae toxin ctx gene [Presence] in Specimen by NAA with probe detection"
* LOINC#48816-3 "Staphylococcus aureus Panton-Valentine leukocidin gene [Presence] in Isolate or Specimen by Molecular genetics method"