ValueSet: MII_VS_Mikrobio_Mikroskopie_Tests_LOINC
Id: mii-vs-mikrobio-mikroskopie-tests-loinc
Title: "MII VS Mikrobio Mikroskopie Tests [LOINC]"
* insert PR_CS_VS_Version
* insert Publisher
* ^status = #active
* $loinc#10680-7 "Herpes simplex virus identified in Cerebral spinal fluid by Electron microscopy"
* $loinc#10681-5 "Herpes simplex virus identified in Tissue by Electron microscopy"
* $loinc#10649-2 "Calicivirus [Identifier] in Stool by Electron microscopy"
* $loinc#76699-8 "Filaria identified in Skin by Light microscopy"
* $loinc#10658-3 "Cyanobacterium identified in Water by Light microscopy"
* $loinc#10646-8 "Astrovirus [Identifier] in Stool by Electron microscopy"
* $loinc#10347-3 "Babesia microti identified in Blood by Light microscopy"
* $loinc#52107-0 "Bacterial capsule [Identifier] in Specimen by Light microscopy"
* $loinc#13325-6 "Bartonella sp identified in Blood by Light microscopy"
* $loinc#10661-7 "Dinoflagellate identified in Water by Light microscopy"
* $loinc#88156-5 "Microscopic observation [Identifier] in Amniotic fluid by Acid fast stain"
* $loinc#87970-0 "Microscopic observation [Identifier] in Amniotic fluid by Giemsa stain"
* $loinc#87971-8 "Microscopic observation [Identifier] in Amniotic fluid by Gram stain"
* $loinc#72408-8 "Microscopic observation [Identifier] in Anal by Gram stain"
* $loinc#88159-9 "Microscopic observation [Identifier] in Aspirate by Acid fast stain"
* $loinc#88684-6 "Microscopic observation [Identifier] in Aspirate by Giemsa stain"
* $loinc#14358-6 "Microscopic observation [Identifier] in Aspirate by Gram stain"
* $loinc#55222-4 "Microscopic observation [Identifier] in Aspirate by Rhodamine-auramine fluorochrome stain"
* $loinc#76082-7 "Microscopic observation [Identifier] in Bronchoalveolar lavage by Methenamine silver nitrate stain"
* $loinc#88231-6 "Microscopic observation [Identifier] in Bile fluid by Acid fast stain"
* $loinc#90261-9 "Microscopic observation [Identifier] in Bile fluid by Giemsa stain"
* $loinc#90262-7 "Microscopic observation [Identifier] in Bile fluid by Gram stain"
* $loinc#32699-1 "Microscopic observation [Identifier] in Blood by Acid fast stain"
* $loinc#29776-2 "Microscopic observation [Identifier] in Blood by Brilliant cresyl blue"
* $loinc#87969-2 "Microscopic observation [Identifier] in Blood by Gram stain"
* $loinc#73694-2 "Microscopic observation [Identifier] in Blood by KOH preparation"
* $loinc#32700-7 "Microscopic observation [Identifier] in Blood by Malaria smear"
* $loinc#33271-8 "Microscopic observation [Identifier] in Blood by Malaria thin smear"
* $loinc#33270-0 "Microscopic observation [Identifier] in Buffy Coat by Light microscopy"
* $loinc#9786-5 "Microscopic observation [Identifier] in Blood or Marrow by Periodic acid-Schiff stain"
* $loinc#32189-3 "Microscopic observation [Identifier] in Body fluid by Acid fast stain"
* $loinc#58944-0 "Microscopic observation [Identifier] in Body fluid by Acid fast stain.Ziehl-Neelsen"
* $loinc#48722-3 "Microscopic observation [Identifier] in Body fluid by Crystal violet stain"
* $loinc#87968-4 "Microscopic observation [Identifier] in Body fluid by Giemsa stain"
* $loinc#27112-2 "Microscopic observation [Identifier] in Body fluid by Gram stain"
* $loinc#68383-9 "Microscopic observation [Identifier] in Body fluid by KOH preparation"
* $loinc#53912-2 "Microscopic observation [Identifier] in Body fluid by Rhodamine-auramine fluorochrome stain"
* $loinc#23901-2 "Microscopic observation [Identifier] in Body fluid by Wet preparation"
* $loinc#88153-2 "Microscopic observation [Identifier] in Bone marrow by Acid fast stain"
* $loinc#87966-8 "Microscopic observation [Identifier] in Bone marrow by Giemsa stain"
* $loinc#87967-6 "Microscopic observation [Identifier] in Bone marrow by Gram stain"
* $loinc#53918-9 "Microscopic observation [Identifier] in Bone marrow by Rhodamine-auramine fluorochrome stain"
* $loinc#10355-6 "Microscopic observation [Identifier] in Bone marrow by Wright Giemsa stain"
* $loinc#24002-8 "Microscopic observation [Identifier] in Bronchial specimen by Acid fast stain"
* $loinc#21021-1 "Microscopic observation [Identifier] in Bronchial specimen by Gram stain"
* $loinc#32811-2 "Microscopic observation [Identifier] in Bronchial specimen by Iron hematoxylin stain"
* $loinc#53522-9 "Microscopic observation [Identifier] in Bronchial specimen by Rhodamine-auramine fluorochrome stain"
* $loinc#87974-2 "Microscopic observation [Identifier] in Burn by Gram stain"
* $loinc#87999-9 "Microscopic observation [Identifier] in Contact lens by Gram stain"
* $loinc#88170-6 "Microscopic observation [Identifier] in Cornea or Conjunctiva by Gram stain"
* $loinc#32190-1 "Microscopic observation [Identifier] in Cerebral spinal fluid"
* $loinc#32188-5 "Microscopic observation [Identifier] in Cerebral spinal fluid by Acid fast stain"
* $loinc#58943-2 "Microscopic observation [Identifier] in Cerebral spinal fluid by Acid fast stain.Ziehl-Neelsen"
* $loinc#59474-7 "Microscopic observation [Identifier] in Cerebral spinal fluid by Acridine orange stain"
* $loinc#87965-0 "Microscopic observation [Identifier] in Cerebral spinal fluid by Giemsa stain"
* $loinc#14357-8 "Microscopic observation [Identifier] in Cerebral spinal fluid by Gram stain"
* $loinc#638-7 "Microscopic observation [Identifier] in Cerebral spinal fluid by India ink prep"
* $loinc#53906-4 "Microscopic observation [Identifier] in Cerebral spinal fluid by Rhodamine-auramine fluorochrome stain"
* $loinc#90282-5 "Microscopic observation [Identifier] in Catheter tip by Gram stain"
* $loinc#89582-1 "Microscopic observation [Identifier] in Cervix by Acid fast stain"
* $loinc#88152-4 "Microscopic observation [Identifier] in Cervix by Acid fast stain.Kinyoun"
* $loinc#6464-2 "Microscopic observation [Identifier] in Cervix by Gram stain"
* $loinc#14355-2 "Microscopic observation [Identifier] in Cervix by KOH preparation"
* $loinc#14318-0 "Microscopic observation [Identifier] in Cervix by Wet preparation"
* $loinc#18326-9 "Microscopic observation [Identifier] in Cervix by Other stain"
* $loinc#21022-9 "Microscopic observation [Identifier] in Dialysis fluid by Gram stain"
* $loinc#88001-3 "Microscopic observation [Identifier] in Peritoneal dialysis fluid by Gram stain"
* $loinc#6465-9 "Microscopic observation [Identifier] in Duodenal fluid by Trichrome stain"
* $loinc#6466-7 "Microscopic observation [Identifier] in Duodenal fluid by Wet preparation"
* $loinc#18327-7 "Microscopic observation [Identifier] in Duodenal fluid by Other stain"
* $loinc#14365-1 "Microscopic observation [Identifier] in Ear by Gram stain"
* $loinc#53914-8 "Microscopic observation [Identifier] in Endometrium by Rhodamine-auramine fluorochrome stain"
* $loinc#14364-4 "Microscopic observation [Identifier] in Eye by Gram stain"
* $loinc#11476-9 "Microscopic observation [Identifier] in Gastric fluid by Acid fast stain"
* $loinc#640-3 "Microscopic observation [Identifier] in Gastric fluid by Acid fast stain.Kinyoun"
* $loinc#641-1 "Microscopic observation [Identifier] in Gastric fluid by Acid fast stain.Kinyoun modified"
* $loinc#642-9 "Microscopic observation [Identifier] in Gastric fluid by Acid fast stain.Ziehl-Neelsen"
* $loinc#20885-0 "Microscopic observation [Identifier] in Gastric fluid by Dark field examination"
* $loinc#53916-3 "Microscopic observation [Identifier] in Gastric fluid by Rhodamine-auramine fluorochrome stain"
* $loinc#88148-2 "Microscopic observation [Identifier] in Genital specimen by Acid fast stain"
* $loinc#91850-8 "Microscopic observation [Identifier] in Genital specimen by Giemsa stain"
* $loinc#48712-4 "Microscopic observation [Identifier] in Genital specimen by Gram stain"
* $loinc#14317-2 "Microscopic observation [Identifier] in Genital specimen by Wet preparation"
* $loinc#6467-5 "Microscopic observation [Identifier] in Genital fluid by Gram stain"
* $loinc#10856-3 "Microscopic observation [Identifier] in Genital mucus by Gram stain"
* $loinc#10688-0 "Microscopic observation [Identifier] in Hair by KOH preparation"
* $loinc#89660-5 "Microscopic observation [Identifier] in Implanted device by Acid fast stain"
* $loinc#89659-7 "Microscopic observation [Identifier] in Implanted device by Gram stain"
* $loinc#87975-9 "Microscopic observation [Identifier] in Isolate by Gram stain"
* $loinc#90269-2 "Microscopic observation [Identifier] in Milk by Acid fast stain"
* $loinc#90263-5 "Microscopic observation [Identifier] in Milk by Gram stain"
* $loinc#10689-8 "Microscopic observation [Identifier] in Nail by KOH preparation"
* $loinc#32026-7 "Microscopic observation [Identifier] in Nose by Gram stain"
* $loinc#88149-0 "Microscopic observation [Identifier] in Nasopharynx by Gram stain"
* $loinc#88155-7 "Microscopic observation [Identifier] in Ocular fluid by Acid fast stain"
* $loinc#88150-8 "Microscopic observation [Identifier] in Ocular fluid by Giemsa stain"
* $loinc#88158-1 "Microscopic observation [Identifier] in Ocular fluid by Gram stain"
* $loinc#32186-9 "Microscopic observation [Identifier] in Penis by Tzanck smear"
* $loinc#88145-8 "Microscopic observation [Identifier] in Pericardial fluid by Acid fast stain"
* $loinc#90267-6 "Microscopic observation [Identifier] in Pericardial fluid by Giemsa stain"
* $loinc#88147-4 "Microscopic observation [Identifier] in Pericardial fluid by Gram stain"
* $loinc#53915-5 "Microscopic observation [Identifier] in Pericardial fluid by Rhodamine-auramine fluorochrome stain"
* $loinc#88144-1 "Microscopic observation [Identifier] in Peritoneal fluid by Acid fast stain"
* $loinc#58945-7 "Microscopic observation [Identifier] in Peritoneal fluid by Acid fast stain.Ziehl-Neelsen"
* $loinc#90268-4 "Microscopic observation [Identifier] in Peritoneal fluid by Giemsa stain"
* $loinc#14359-4 "Microscopic observation [Identifier] in Peritoneal fluid by Gram stain"
* $loinc#53910-6 "Microscopic observation [Identifier] in Peritoneal fluid by Rhodamine-auramine fluorochrome stain"
* $loinc#88146-6 "Microscopic observation [Identifier] in Placenta by Gram stain"
* $loinc#14353-7 "Microscopic observation [Identifier] in Pleural fluid by Acid fast stain.Kinyoun modified"
* $loinc#58942-4 "Microscopic observation [Identifier] in Pleural fluid by Acid fast stain.Ziehl-Neelsen"
* $loinc#88000-5 "Microscopic observation [Identifier] in Pleural fluid by Giemsa stain"
* $loinc#14360-2 "Microscopic observation [Identifier] in Pleural fluid by Gram stain"
* $loinc#53907-2 "Microscopic observation [Identifier] in Pleural fluid by Rhodamine-auramine fluorochrome stain"
* $loinc#643-7 "Microscopic observation [Identifier] in Pus by Gram stain"
* $loinc#89662-1 "Microscopic observation [Identifier] in Lower respiratory specimen by Acid fast stain"
* $loinc#88633-3 "Microscopic observation [Identifier] in Lower respiratory specimen by Giemsa stain"
* $loinc#88632-5 "Microscopic observation [Identifier] in Lower respiratory specimen by Gram stain"
* $loinc#88685-3 "Microscopic observation [Identifier] in Lower respiratory specimen by KOH preparation"
* $loinc#89658-9 "Microscopic observation [Identifier] in Lower respiratory specimen by Methenamine silver nitrate stain"
* $loinc#89657-1 "Microscopic observation [Identifier] in Lower respiratory specimen by Toluidine blue O stain"
* $loinc#89661-3 "Microscopic observation [Identifier] in Upper respiratory specimen by Acid fast stain"
* $loinc#91808-6 "Microscopic observation [Identifier] in Upper respiratory specimen by Gram stain"
* $loinc#88634-1 "Microscopic observation [Identifier] in Saliva (oral fluid) by Gram stain"
* $loinc#88157-3 "Microscopic observation [Identifier] in Semen by Acid fast stain"
* $loinc#87973-4 "Microscopic observation [Identifier] in Semen by Gram stain"
* $loinc#88154-0 "Microscopic observation [Identifier] in Sinus by Acid fast stain"
* $loinc#87972-6 "Microscopic observation [Identifier] in Sinus by Gram stain"
* $loinc#94543-6 "Microscopic observation [Identifier] in Skin by Acid fast stain"
* $loinc#90296-5 "Microscopic observation [Identifier] in Skin by Gram stain"
* $loinc#644-5 "Microscopic observation [Identifier] in Skin by KOH preparation"
* $loinc#32187-7 "Microscopic observation [Identifier] in Skin by Tzanck smear"
* $loinc#11477-7 "Microscopic observation [Identifier] in Sputum by Acid fast stain"
* $loinc#645-2 "Microscopic observation [Identifier] in Sputum by Acid fast stain.Kinyoun"
* $loinc#646-0 "Microscopic observation [Identifier] in Sputum by Acid fast stain.Kinyoun modified"
* $loinc#647-8 "Microscopic observation [Identifier] in Sputum by Acid fast stain.Ziehl-Neelsen"
* $loinc#6468-3 "Microscopic observation [Identifier] in Sputum by Calcofluor white"
* $loinc#648-6 "Microscopic observation [Identifier] in Sputum by Gram stain"
* $loinc#17281-7 "Microscopic observation [Identifier] in Sputum by KOH preparation"
* $loinc#53904-9 "Microscopic observation [Identifier] in Sputum by Rhodamine-auramine fluorochrome stain"
* $loinc#11478-5 "Microscopic observation [Identifier] in Stool by Acid fast stain"
* $loinc#20884-3 "Microscopic observation [Identifier] in Stool by Dark field examination"
* $loinc#649-4 "Microscopic observation [Identifier] in Stool by Gram stain"
* $loinc#8250-3 "Microscopic observation [Identifier] in Stool by Electron microscopy"
* $loinc#20882-7 "Microscopic observation [Identifier] in Stool by Electron microscopy negative stain"
* $loinc#6469-1 "Microscopic observation [Identifier] in Stool by Trichrome stain"
* $loinc#6470-9 "Microscopic observation [Identifier] in Stool by Wet preparation"
* $loinc#63433-7 "Microscopic observation [Identifier] in Synovial fluid by Acid fast stain.Ziehl-Neelsen"
* $loinc#88235-7 "Microscopic observation [Identifier] in Synovial fluid by Giemsa stain"
* $loinc#14363-6 "Microscopic observation [Identifier] in Synovial fluid by Gram stain"
* $loinc#53913-0 "Microscopic observation [Identifier] in Synovial fluid by Rhodamine-auramine fluorochrome stain"
* $loinc#75222-0 "Microscopic observation [Identifier] in Throat by Alberts stain"
* $loinc#14362-8 "Microscopic observation [Identifier] in Throat by Gram stain"
* $loinc#11479-3 "Microscopic observation [Identifier] in Tissue by Acid fast stain"
* $loinc#6655-5 "Microscopic observation [Identifier] in Tissue by Acid fast stain.Kinyoun"
* $loinc#6656-3 "Microscopic observation [Identifier] in Tissue by Acid fast stain.Kinyoun modified"
* $loinc#6657-1 "Microscopic observation [Identifier] in Tissue by Acid fast stain.Ziehl-Neelsen"
* $loinc#6658-9 "Microscopic observation [Identifier] in Tissue by Acridine orange stain"
* $loinc#6472-5 "Microscopic observation [Identifier] in Tissue by Calcofluor white"
* $loinc#6659-7 "Microscopic observation [Identifier] in Tissue by Carbol-fuchsin stain"
* $loinc#6607-6 "Microscopic observation [Identifier] in Tissue by Dark field examination"
* $loinc#6661-3 "Microscopic observation [Identifier] in Tissue by Dry mount"
* $loinc#6662-1 "Microscopic observation [Identifier] in Tissue by Giemsa stain"
* $loinc#6663-9 "Microscopic observation [Identifier] in Tissue by Gimenez stain"
* $loinc#6664-7 "Microscopic observation [Identifier] in Tissue by Gram stain"
* $loinc#6665-4 "Microscopic observation [Identifier] in Tissue by Hematoxylin and eosin stain"
* $loinc#6666-2 "Microscopic observation [Identifier] in Tissue by India ink prep"
* $loinc#6667-0 "Microscopic observation [Identifier] in Tissue by KOH preparation"
* $loinc#6669-6 "Microscopic observation [Identifier] in Tissue by Macchiavello stain"
* $loinc#6670-4 "Microscopic observation [Identifier] in Tissue by Malaria smear"
* $loinc#6671-2 "Microscopic observation [Identifier] in Tissue by Methenamine silver nitrate stain"
* $loinc#6672-0 "Microscopic observation [Identifier] in Tissue by Methylene blue stain.Loeffler"
* $loinc#6668-8 "Microscopic observation [Identifier] in Tissue by M'Fadyean stain"
* $loinc#20881-9 "Microscopic observation [Identifier] in Tissue by Electron microscopy thin sectiion"
* $loinc#6673-8 "Microscopic observation [Identifier] in Tissue by Neisser stain"
* $loinc#10637-7 "Microscopic observation [Identifier] in Tissue by Night blue stain"
* $loinc#6675-3 "Microscopic observation [Identifier] in Tissue by Periodic acid-Schiff stain"
* $loinc#6677-9 "Microscopic observation [Identifier] in Tissue by Rhodamine-auramine fluorochrome stain"
* $loinc#6473-3 "Microscopic observation [Identifier] in Tissue by Trichrome stain"
* $loinc#6679-5 "Microscopic observation [Identifier] in Tissue by Warthin-Starry stain"
* $loinc#6680-3 "Microscopic observation [Identifier] in Tissue by Wet preparation"
* $loinc#6681-1 "Microscopic observation [Identifier] in Tissue by Wright stain"
* $loinc#6471-7 "Microscopic observation [Identifier] in Tissue by Other stain"
* $loinc#6474-1 "Microscopic observation [Identifier] in Urethra by Gram stain"
* $loinc#57851-8 "Microscopic observation [Identifier] in Urethra by Wet preparation"
* $loinc#11480-1 "Microscopic observation [Identifier] in Urine by Acid fast stain"
* $loinc#650-2 "Microscopic observation [Identifier] in Urine by Acid fast stain.Kinyoun"
* $loinc#651-0 "Microscopic observation [Identifier] in Urine by Acid fast stain.Kinyoun modified"
* $loinc#652-8 "Microscopic observation [Identifier] in Urine by Acid fast stain.Ziehl-Neelsen"
* $loinc#20883-5 "Microscopic observation [Identifier] in Urine by Dark field examination"
* $loinc#653-6 "Microscopic observation [Identifier] in Urine by Gram stain"
* $loinc#68958-8 "Microscopic observation [Identifier] in Urine by KOH preparation"
* $loinc#53905-6 "Microscopic observation [Identifier] in Urine by Rhodamine-auramine fluorochrome stain"
* $loinc#14361-0 "Microscopic observation [Identifier] in Vaginal fluid by Gram stain"
* $loinc#14356-0 "Microscopic observation [Identifier] in Vaginal fluid by KOH preparation"
* $loinc#14319-8 "Microscopic observation [Identifier] in Vaginal fluid by Wet preparation"
* $loinc#88635-8 "Microscopic observation [Identifier] in Vomitus by Gram stain"
* $loinc#88151-6 "Microscopic observation [Identifier] in Wound by Acid fast stain"
* $loinc#14354-5 "Microscopic observation [Identifier] in Wound by Acid fast stain.Kinyoun modified"
* $loinc#10357-2 "Microscopic observation [Identifier] in Wound by Gram stain"
* $loinc#11545-1 "Microscopic observation [Identifier] in Specimen by Acid fast stain"
* $loinc#654-4 "Microscopic observation [Identifier] in Specimen by Acid fast stain.Kinyoun"
* $loinc#655-1 "Microscopic observation [Identifier] in Specimen by Acid fast stain.Kinyoun modified"
* $loinc#656-9 "Microscopic observation [Identifier] in Specimen by Acid fast stain.Ziehl-Neelsen"
* $loinc#657-7 "Microscopic observation [Identifier] in Specimen by Acridine orange stain"
* $loinc#658-5 "Microscopic observation [Identifier] in Specimen by Calcofluor white"
* $loinc#659-3 "Microscopic observation [Identifier] in Specimen by Carbol-fuchsin stain"
* $loinc#660-1 "Microscopic observation [Identifier] in Specimen by Dark field examination"
* $loinc#661-9 "Microscopic observation [Identifier] in Specimen by Dry mount"
* $loinc#662-7 "Microscopic observation [Identifier] in Specimen by Giemsa stain"
* $loinc#663-5 "Microscopic observation [Identifier] in Specimen by Gimenez stain"
* $loinc#664-3 "Microscopic observation [Identifier] in Specimen by Gram stain"
* $loinc#665-0 "Microscopic observation [Identifier] in Specimen by Hematoxylin and eosin stain"
* $loinc#35347-4 "Microscopic observation [Identifier] in Specimen by Immunofluorescence"
* $loinc#666-8 "Microscopic observation [Identifier] in Specimen by India ink prep"
* $loinc#14841-1 "Microscopic observation [Identifier] in Specimen by Iron hematoxylin stain"
* $loinc#14842-9 "Microscopic observation [Identifier] in Specimen by Kinyoun iron hematoxylin stain"
* $loinc#667-6 "Microscopic observation [Identifier] in Specimen by KOH preparation"
* $loinc#51700-3 "Microscopic observation [Identifier] in Specimen by Lactophenol blue"
* $loinc#669-2 "Microscopic observation [Identifier] in Specimen by Macchiavello stain"
* $loinc#33699-0 "Microscopic observation [Identifier] in Specimen by Malachite green stain"
* $loinc#670-0 "Microscopic observation [Identifier] in Specimen by Methenamine silver nitrate stain"
* $loinc#671-8 "Microscopic observation [Identifier] in Specimen by Methylene blue stain.Loeffler"
* $loinc#668-4 "Microscopic observation [Identifier] in Specimen by M'Fadyean stain"
* $loinc#34166-9 "Microscopic observation [Identifier] in Specimen by Electron microscopy"
* $loinc#672-6 "Microscopic observation [Identifier] in Specimen by Neisser stain"
* $loinc#674-2 "Microscopic observation [Identifier] in Specimen by Periodic acid-Schiff stain"
* $loinc#676-7 "Microscopic observation [Identifier] in Specimen by Rhodamine-auramine fluorochrome stain"
* $loinc#20431-3 "Microscopic observation [Identifier] in Specimen by Smear"
* $loinc#677-5 "Microscopic observation [Identifier] in Specimen by Toluidine blue O stain"
* $loinc#678-3 "Microscopic observation [Identifier] in Specimen by Trichrome stain"
* $loinc#45043-7 "Microscopic observation [Identifier] in Specimen by Tzanck smear"
* $loinc#679-1 "Microscopic observation [Identifier] in Specimen by Warthin-Starry stain"
* $loinc#44098-2 "Microscopic observation [Identifier] in Specimen by Wayson stain"
* $loinc#680-9 "Microscopic observation [Identifier] in Specimen by Wet preparation"
* $loinc#682-5 "Microscopic observation [Identifier] in Specimen by Wright Giemsa stain"
* $loinc#681-7 "Microscopic observation [Identifier] in Specimen by Wright stain"
* $loinc#11546-9 "Microscopic observation [Identifier] in Specimen by Other stain"
* $loinc#79375-2 "Microscopic observation [Identifier] in Sputum by Acid fast stain.Ziehl-Neelsen--2nd specimen"
* $loinc#79376-0 "Microscopic observation [Identifier] in Sputum by Acid fast stain.Ziehl-Neelsen--3rd specimen"
* $loinc#10857-1 "Microsporidia identified in Specimen by Light microscopy"
* $loinc#88337-1 "Mite identified in Ear by Light microscopy"
* $loinc#10692-2 "Mushroom.toxic identified in Food by Light microscopy"
* $loinc#10693-0 "Mushroom.toxic identified in Vomitus by Light microscopy"
* $loinc#10696-3 "Norovirus [Identifier] in Stool by Electron microscopy"
* $loinc#10700-3 "Orthopoxvirus [Identifier] in Skin by Electron microscopy"
* $loinc#10855-5 "Ova and parasites identified in Duodenal fluid or Gastric fluid by Light microscopy"
* $loinc#91826-8 "Ova and parasites identified in Lower respiratory specimen by Light microscopy"
* $loinc#91768-2 "Ova and parasites identified in Sputum by Light microscopy"
* $loinc#10704-5 "Ova and parasites identified in Stool by Light microscopy"
* $loinc#6674-6 "Ova and parasites identified in Tissue by Light microscopy"
* $loinc#673-4 "Ova and parasites identified in Specimen by Light microscopy"
* $loinc#13319-9 "Ova and parasites identified in Stool by Light microscopy--2nd specimen"
* $loinc#52795-2 "Ova and parasites identified in Specimen by Light microscopy--2nd specimen"
* $loinc#13320-7 "Ova and parasites identified in Stool by Light microscopy--3rd specimen"
* $loinc#52794-5 "Ova and parasites identified in Specimen by Light microscopy--3rd specimen"
* $loinc#17784-0 "Parasite identified in Blood by Light microscopy"
* $loinc#53609-4 "Parasite identified in Bone marrow by Light microscopy"
* $loinc#98026-8 "Parasite identified in Prostatic fluid by Light microscopy"
* $loinc#20933-8 "Parasite identified in Serum by Light microscopy"
* $loinc#10706-0 "Picornavirus [Identifier] in Stool by Electron microscopy"
* $loinc#10708-6 "Toxic Plant identified in Vomitus by Light microscopy"
* $loinc#32206-5 "Plasmodium sp identified in Blood by Light microscopy"
* $loinc#41451-6 "Plasmodium stage [Identifier] in Blood by Light microscopy"
* $loinc#13326-4 "Pneumocystis sp identified in Specimen by Light microscopy"
* $loinc#9787-3 "Sarcoptes scabiei identified in Skin by Light microscopy"
* $loinc#76767-3 "Schistosoma sp identified in Semen by Light microscopy"
* $loinc#10715-1 "Schistosoma sp identified in Urine sediment by Light microscopy"
* $loinc#10722-7 "Torovirus [Identifier] in Stool by Electron microscopy"
* $loinc#74037-3 "Transmissible spongiform encephalopathy [Identifier] in Brain by Light microscopy"
* $loinc#10729-2 "Trypanosoma sp identified in Blood by Light microscopy"
* $loinc#14839-5 "Trypanosoma sp identified in Buffy Coat by Light microscopy"
* $loinc#10734-2 "Varicella zoster virus identified in Skin by Electron microscopy"
* $loinc#10736-7 "Virus identified in Cerebral spinal fluid by Electron microscopy"
* $loinc#10737-5 "Virus identified in Stool by Electron microscopy"
* $loinc#10738-3 "Virus identified in Tissue by Electron microscopy"
* $loinc#10739-1 "Virus identified in Specimen by Electron microscopy"
* $loinc#24421-0 "Haemobartonella felis [Presence] in Blood by Light microscopy"
* $loinc#22971-6 "Caprine arthritis encephalitis virus [Presence] in Specimen by Electron microscopy"
* $loinc#88344-7 "Intracellular bacteria [Presence] in Ear by Light microscopy"
* $loinc#32158-8 "Klebsiella granulomatis [Presence] in Genital specimen by Light microscopy"
* $loinc#43400-1 "Lactobacillus sp morphotypes [Presence] in Vaginal fluid by Light microscopy"
* $loinc#23212-4 "Lumpy skin disease virus [Presence] in Tissue by Electron microscopy"
* $loinc#48982-3 "Ehrlichia sp [Presence] in Specimen by Light microscopy"
* $loinc#88338-9 "Coccal bacteria [Presence] in Ear by Light microscopy"
* $loinc#23016-9 "Coxiella burnetii [Presence] in Placenta by Light microscopy"
* $loinc#44275-6 "Coxiella burnetii [Presence] in Specimen by Light microscopy"
* $loinc#16719-7 "Cytomegalovirus inclusion bodies [Presence] in Urine by Microscopic observation"
* $loinc#7809-7 "Astrovirus [Presence] in Stool by Electron microscopy"
* $loinc#22811-4 "Avian infectious laryngotracheitis virus [Presence] in Specimen by Electron microscopy"
* $loinc#22836-1 "Avian pox virus [Presence] in Tissue by Electron microscopy"
* $loinc#88339-7 "Bacilliform bacteria [Presence] in Ear by Light microscopy"
* $loinc#96601-0 "Bacilliform bacteria [Presence] in Skin by Light microscopy"
* $loinc#95074-1 "Bacteria [Presence] in Bronchoalveolar lavage by Light microscopy"
* $loinc#41599-2 "Bacteria [Presence] in Body fluid by Light microscopy"
* $loinc#41602-4 "Bacteria [Presence] in Cerebral spinal fluid by Light microscopy"
* $loinc#44039-6 "Bacteria [Presence] in Eye by Light microscopy"
* $loinc#18192-5 "Bacteria [Presence] in Nose by Light microscopy"
* $loinc#41598-4 "Bacteria [Presence] in Pericardial fluid by Light microscopy"
* $loinc#41601-6 "Bacteria [Presence] in Peritoneal fluid by Light microscopy"
* $loinc#41603-2 "Bacteria [Presence] in Pleural fluid by Light microscopy"
* $loinc#41600-8 "Bacteria [Presence] in Synovial fluid by Light microscopy"
* $loinc#22993-0 "Chlamydophila psittaci [Presence] in Placenta by Electron microscopy"
* $loinc#22808-0 "Infectious bronchitis virus [Presence] in Specimen by Electron microscopy"
* $loinc#23381-7 "Abnormal Prion Protein [Presence] in Brain by Electron microscopy"
* $loinc#48981-5 "Anaplasma sp [Presence] in Specimen by Light microscopy"
* $loinc#88342-1 "Malassezia sp [Presence] in Ear by Light microscopy"
* $loinc#23573-9 "Rabbit hemorrhagic disease virus [Presence] in Tissue by Electron microscopy"
* $loinc#23388-2 "Rabies virus [Presence] in Brain by Light microscopy"
* $loinc#51783-9 "Reagin Ab [Presence] in Cord blood by VDRL"
* $loinc#5290-2 "Reagin Ab [Presence] in Cerebral spinal fluid by VDRL"
* $loinc#5292-8 "Reagin Ab [Presence] in Serum by VDRL"
* $loinc#21030-2 "Reagin Ab [Presence] in Serum from Donor by VDRL"
* $loinc#14904-7 "Reagin Ab [Presence] in Specimen by VDRL"
* $loinc#23030-0 "Duck enteritis virus [Presence] in Tissue by Electron microscopy"
* $loinc#43398-7 "Gardnerella vaginalis+Prevotella sp morphotypes [Presence] in Vaginal fluid by Light microscopy"
* $loinc#76083-5 "Microscopic observation [Presence] in Bronchoalveolar lavage by Acid fast stain.Ziehl-Neelsen"
* $loinc#88171-4 "Microscopic observation [Presence] in Cornea or Conjunctiva by Acid fast stain"
* $loinc#88172-2 "Microscopic observation [Presence] in Isolate by Acid fast stain"
* $loinc#88173-0 "Microscopic observation [Presence] in Pleural fluid by Acid fast stain"
* $loinc#88631-7 "Microscopic observation [Presence] in Lower respiratory specimen by Acid fast stain.Kinyoun"
* $loinc#88234-0 "Microscopic observation [Presence] in Synovial fluid by Acid fast stain"
* $loinc#88366-0 "Microscopic observation [Presence] in Vomitus by Acid fast stain"
* $loinc#72357-7 "Microscopic observation [Presence] in Specimen by Acid fast stain"
* $loinc#87243-2 "Microscopic observation [Presence] in Specimen by Auramine fluorochrome stain"
* $loinc#94856-2 "Microscopic observation [Presence] in Sputum by Acid fast stain --2nd specimen"
* $loinc#94857-0 "Microscopic observation [Presence] in Sputum by Acid fast stain --3rd specimen"
* $loinc#88340-5 "Mite [Presence] in Ear by Light microscopy"
* $loinc#7973-1 "Norovirus [Presence] in Stool by Electron microscopy"
* $loinc#91900-1 "Parasite [Presence] in Blood by Light microscopy"
* $loinc#51587-4 "Plasmodium sp [Presence] in Blood by Light microscopy"
* $loinc#20949-4 "Rickettsia sp [Presence] in Blood by Light microscopy"
* $loinc#8011-9 "Rotavirus [Presence] in Stool by Electron microscopy"
* $loinc#38275-4 "Transmissible spongiform encephalopathy [Presence] in Brain by Light microscopy"
* $loinc#23499-7 "Trichinella spiralis [Presence] in Tissue by Light microscopy"
* $loinc#91845-8 "Trichomonas vaginalis [Presence] in Genital specimen by Light microscopy"
* $loinc#72277-7 "Trichomonas vaginalis [Presence] in Prostatic fluid by Light microscopy"
* $loinc#90286-6 "Trichomonas vaginalis [Presence] in Vaginal fluid by Light microscopy"
* $loinc#41222-1 "Yeast [Presence] in Body fluid by Light microscopy"
* $loinc#41242-9 "Yeast [Presence] in Cerebral spinal fluid by Light microscopy"
* $loinc#80725-5 "Trichomonas sp [Presence] in Semen by Light microscopy"
* $loinc#32724-7 "Trichomonas sp [Presence] in Urine by Light microscopy"
* $loinc#90303-9 "Trichomonas vaginalis [Presence] in Cervix by Light microscopy"
* $loinc#23509-3 "Trypanosoma equiperdum [Presence] in Body fluid by Light microscopy"
* $loinc#17773-3 "Yeast [Presence] in Stool by Light microscopy"