ValueSet: MII_VS_Mikrobio_Resistenzmutation_LOINC
Id: mii-vs-mikrobio-resistenzmutation-loinc
Title: "MII VS Mikrobio Resistenzmutation [LOINC]"
* insert PR_CS_VS_Version
* insert Publisher
* ^status = #active
* ^date = "2023-03-02T00:00:00Z"
* $loinc#92243-5 "Microorganism resistance mutation tested for by Molecular method"
* $loinc#89371-9 "MTB complex DNA and rpoB RIF resistance mutation panel [Presence]"
* $loinc#94057-7 "Bacterial ahpC gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#94064-3 "Bacterial eis gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#94058-5 "Bacterial embB gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#94056-9 "Bacterial fabG1 gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#94061-9 "Bacterial gidB gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#94060-1 "Bacterial gyrA gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#101576-7 "Bacterial gyrB gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#94055-1 "Bacterial inhA gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#94054-4 "Arzneimittel-Resistenzmutation im bakteriellen katG-Gen [Nachweis oder Identität] mittels Molekulargenetik"
* $loinc#94059-3 "Bacterial pncA gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#94065-0 "Bacterial rpoB gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#94063-5 "Bacterial rpsL gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#94062-7 "Bacterial rrs gene drug resistance mutation [Identifier] by Molecular method"
* $loinc#92248-4 "Microorganism resistance mutation amino acid change by Molecular method"
* $loinc#92246-8 "Microorganism resistance mutation detected [Presence] by Molecular method"
* $loinc#92245-0 "Microorganism resistance mutation nucleic acid change by Molecular method"
* $loinc#92247-6 "Microorganism resistance mutation amino acid change type by Molecular method"
* $loinc#92244-3 "Microorganism resistance mutation nucleic acid change type by Molecular method"
* $loinc#72864-2 "Mycobacterium tuberculosis rpsL+rrs genes aminoglycoside resistance mutation [Presence] by Molecular method"
* $loinc#88509-5 "Helicobacter pylori 23S rRNA clarithromycin resistance mutation [Identifier] by Molecular method"
* $loinc#89314-9 "Bacterial 23S rRNA gene azithromycin resistance mutation [Presence] by Molecular method"
* $loinc#72868-3 "Mycobacterium leprae folP1 gene dapsone resistance mutation [Presence] by Molecular method"
* $loinc#72869-1 "Mycobacterium leprae gyrA gene fluoroquinolone resistance mutation [Presence] by Molecular method"
* $loinc#72863-4 "Mycobacterium leprae gyrB gene fluoroquinolone resistance mutation [Presence] by Molecular method"
* $loinc#72870-9 "Mycobacterium leprae rpoB gene rifAMPin resistance mutation [Presence] by Molecular method"
* $loinc#46247-3 "Mycobacterium tuberculosis embB gene ethambutol resistance mutation [Identifier] by Molecular method"
* $loinc#72866-7 "Mycobacterium tuberculosis ethA gene ethionamide resistance mutation [Presence] by Molecular method"
* $loinc#72865-9 "Mycobacterium tuberculosis ethB gene ethionamide resistance mutation [Presence] by Molecular method"
* $loinc#72276-9 "Mycobacterium tuberculosis gyrA gene fluoroquinolone resistance mutation [Presence] by Molecular method"
* $loinc#72867-5 "Mycobacterium tuberculosis gyrB gene fluoroquinolone resistance mutation [Presence] by Molecular method"
* $loinc#46245-7 "Mycobacterium tuberculosis pncA gene pyrazinamide resistance mutation [Identifier] by Molecular method"
* $loinc#89372-7 "Mycobacterium tuberculosis complex rpoB gene rifAMPin resistance mutation [Presence] by Molecular method"
* $loinc#46244-0 "Mycobacterium tuberculosis complex rpoB gene rifAMPin resistance mutation identified by Molecular method"
* $loinc#63072-3 "Mycobacterium tuberculosis inhA gene isoniazid low level resistance mutation [Presence] by Molecular method"
* $loinc#46246-5 "Mycobacterium tuberculosis katG gene isoniazid high level resistance mutation [Identifier] by Molecular method"
* $loinc#48175-4 "Mycobacterium tuberculosis katG + inhA gene isoniazid resistance mutation [Presence] by Molecular method"
* $loinc#74004-3 "ABCB1 gene mutations found [Identifier] in Blood or Tissue by Molecular genetics method Nominal"
* $loinc#72506-9 "ABCB1 gene c.3435C>T [Presence] in Blood or Tissue by Molecular genetics method"