ValueSet: MII_VS_Mikrobio_Resistenzmutation_LOINC
Id: mii-vs-mikrobio-resistenzmutation-loinc
Title: "MII VS Mikrobio Resistenzmutation [LOINC]"
* ^status = #active
* ^version = "2025.0.0"
* ^date = "2023-03-02T00:00:00Z"
* LOINC#92243-5 "Microorganism resistance mutation tested for by Molecular method"
* LOINC#89371-9 "MTB complex DNA and rpoB RIF resistance mutation panel [Presence]"
* LOINC#94057-7 "Bacterial ahpC gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94064-3 "Bacterial eis gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94058-5 "Bacterial embB gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94056-9 "Bacterial fabG1 gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94061-9 "Bacterial gidB gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94060-1 "Bacterial gyrA gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#101576-7 "Bacterial gyrB gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94055-1 "Bacterial inhA gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94054-4 "Bacterial katG gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94059-3 "Bacterial pncA gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94065-0 "Bacterial rpoB gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94063-5 "Bacterial rpsL gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#94062-7 "Bacterial rrs gene drug resistance mutation [Identifier] by Molecular method"
* LOINC#92248-4 "Microorganism resistance mutation amino acid change by Molecular method"
* LOINC#92246-8 "Microorganism resistance mutation detected [Presence] by Molecular method"
* LOINC#92245-0 "Microorganism resistance mutation nucleic acid change by Molecular method"
* LOINC#92247-6 "Microorganism resistance mutation amino acid change type by Molecular method"
* LOINC#92244-3 "Microorganism resistance mutation nucleic acid change type by Molecular method"
* LOINC#72864-2 "Mycobacterium tuberculosis rpsL+rrs genes aminoglycoside resistance mutation [Presence] by Molecular method"
* LOINC#88509-5 "Helicobacter pylori 23S rRNA clarithromycin resistance mutation [Identifier] by Molecular method"
* LOINC#89314-9 "Bacterial 23S rRNA gene azithromycin resistance mutation [Presence] by Molecular method"
* LOINC#72868-3 "Mycobacterium leprae folP1 gene dapsone resistance mutation [Presence] by Molecular method"
* LOINC#72869-1 "Mycobacterium leprae gyrA gene fluoroquinolone resistance mutation [Presence] by Molecular method"
* LOINC#72863-4 "Mycobacterium leprae gyrB gene fluoroquinolone resistance mutation [Presence] by Molecular method"
* LOINC#72870-9 "Mycobacterium leprae rpoB gene rifAMPin resistance mutation [Presence] by Molecular method"
* LOINC#46247-3 "Mycobacterium tuberculosis embB gene ethambutol resistance mutation [Identifier] by Molecular method"
* LOINC#72866-7 "Mycobacterium tuberculosis ethA gene ethionamide resistance mutation [Presence] by Molecular method"
* LOINC#72865-9 "Mycobacterium tuberculosis ethB gene ethionamide resistance mutation [Presence] by Molecular method"
* LOINC#72276-9 "Mycobacterium tuberculosis gyrA gene fluoroquinolone resistance mutation [Presence] by Molecular method"
* LOINC#72867-5 "Mycobacterium tuberculosis gyrB gene fluoroquinolone resistance mutation [Presence] by Molecular method"
* LOINC#46245-7 "Mycobacterium tuberculosis pncA gene pyrazinamide resistance mutation [Identifier] by Molecular method"
* LOINC#89372-7 "Mycobacterium tuberculosis complex rpoB gene rifAMPin resistance mutation [Presence] by Molecular method"
* LOINC#46244-0 "Mycobacterium tuberculosis complex rpoB gene rifAMPin resistance mutation identified by Molecular method"
* LOINC#63072-3 "Mycobacterium tuberculosis inhA gene isoniazid low level resistance mutation [Presence] by Molecular method"
* LOINC#46246-5 "Mycobacterium tuberculosis katG gene isoniazid high level resistance mutation [Identifier] by Molecular method"
* LOINC#48175-4 "Mycobacterium tuberculosis katG + inhA gene isoniazid resistance mutation [Presence] by Molecular method"
* LOINC#74004-3 "ABCB1 gene mutations found [Identifier] in Blood or Tissue by Molecular genetics method Nominal"
* LOINC#72506-9 "ABCB1 gene c.3435C>T [Presence] in Blood or Tissue by Molecular genetics method"