ValueSet: MII_VS_Mikrobio_Kulturtests_LOINC
Id: mii-vs-mikrobio-kulturtests-loinc
Title: "MII VS Mikrobio Kulturtests [LOINC]"
* insert PR_CS_VS_Version
* insert Publisher
* ^status = #active
* ^contact.telecom.system = #email
* $loinc#19127-0 "Bacteria identified in Sputum by Acute Respiratoy Distress (ARDS) culture"
* $loinc#636-1 "Bacteria identified in Specimen by Sterile body fluid culture"
* $loinc#45275-5 "Bacteria identified in Blood by Aerobe culture 25 degree C incubation"
* $loinc#79425-5 "Bacteria identified in Lower respiratory specimen by Cystic fibrosis respiratory culture"
* $loinc#623-9 "Bacteria identified in Sputum by Cystic fibrosis respiratory culture"
* $loinc#14325-5 "Bacteria identified in Specimen by Environmental culture"
* $loinc#10668-2 "Fungus identified in Specimen by Environmental culture"
* $loinc#45276-3 "Bacteria identified in Blood by Anaerobe culture 25 degree C incubation"
* $loinc#20474-3 "Bacteria identified in Tissue by Biopsy culture"
* $loinc#14788-4 "Helminth+Arthropod identified in Specimen by Rearing/Culture"
* $loinc#616-3 "Bacteria identified in Line specimen by IV Line culture"
* $loinc#17942-4 "Bacteria # 2 identified in Line specimen by IV Line culture"
* $loinc#17943-2 "Bacteria # 3 identified in Line specimen by IV Line culture"
* $loinc#17944-0 "Bacteria # 4 identified in Line specimen by IV Line culture"
* $loinc#17945-7 "Bacteria # 5 identified in Line specimen by IV Line culture"
* $loinc#17946-5 "Bacteria # 6 identified in Line specimen by IV Line culture"
* $loinc#75357-4 "Bacteria identified in Abscess by Anaerobe+Aerobe culture"
* $loinc#624-7 "Bacteria identified in Sputum by Respiratory culture"
* $loinc#75269-1 "Bacteria identified in Genital specimen by Anaerobe+Aerobe culture"
* $loinc#32355-0 "Bacteria identified in Specimen by Respiratory culture"
* $loinc#74816-0 "Bacteria identified in Eye by Anaerobe+Aerobe culture"
* $loinc#48561-5 "Bacteria # 2 identified in Specimen by Respiratory culture"
* $loinc#48562-3 "Bacteria # 3 identified in Specimen by Respiratory culture"
* $loinc#48563-1 "Bacteria # 4 identified in Specimen by Respiratory culture"
* $loinc#48564-9 "Bacteria # 5 identified in Specimen by Respiratory culture"
* $loinc#48565-6 "Bacteria # 6 identified in Specimen by Respiratory culture"
* $loinc#48566-4 "Bacteria # 7 identified in Specimen by Respiratory culture"
* $loinc#75358-2 "Bacteria identified in Bone by Anaerobe+Aerobe culture"
* $loinc#20896-7 "Mycoplasma sp [Presence] in Tissue by Culture NPIP (National Poultry Improvement Plan)"
* $loinc#75359-0 "Bacteria identified in Bone marrow by Anaerobe+Aerobe culture"
* $loinc#21020-3 "Bacteria identified in Specimen by Anaerobe+Aerobe culture"
* $loinc#46131-9 "Clostridioides difficile toxin B [Presence] in Stool by Cytotoxin tissue culture assay"
* $loinc#20692-0 "Bacillus cereus [Presence] in Food by Culture FDA method"
* $loinc#89655-5 "Virus identified in Tissue by Shell vial culture"
* $loinc#6362-8 "Clostridioides difficile toxin A+B [Presence] in Stool by Cytotoxin tissue culture assay"
* $loinc#20811-6 "Escherichia coli [Presence] in Specimen by Culture FDA method"
* $loinc#86337-3 "Virus identified in Isolate by Shell vial culture"
* $loinc#50024-9 "Virus identified in Specimen by Shell vial culture"
* $loinc#90426-8 "Microorganism preliminary growth [Presence] in Blood by Aerobic culture with antimicrobial neutralizer"
* $loinc#90427-6 "Microorganism preliminary growth [Presence] in Blood by Anaerobic culture with antimicrobial neutralizer"
* $loinc#43697-2 "Herpes simplex virus identified in Specimen by Shell vial culture"
* $loinc#43695-6 "Herpes virus identified in Specimen by Shell vial culture"
* $loinc#43699-8 "Enterovirus identified in Cerebral spinal fluid by Shell vial culture"
* $loinc#43698-0 "Enterovirus identified in Specimen by Shell vial culture"
* $loinc#49538-2 "Influenza virus identified in Specimen by Shell vial culture"
* $loinc#43696-4 "Herpes simplex virus identified in Cerebral spinal fluid by Shell vial culture"
* $loinc#43693-1 "Varicella zoster virus identified in Skin by Shell vial culture"
* $loinc#90428-4 "Microorganism preliminary growth [Presence] in Body fluid by Aerobic culture with antimicrobial neutralizer"
* $loinc#90431-8 "Microorganism preliminary growth [Presence] in Body fluid by Anaerobic culture with antimicrobial neutralizer"
* $loinc#80204-1 "Influenza virus A and B identified in Nasopharynx by Shell vial culture"
* $loinc#87943-7 "Bacteria identified in Sinus by Anaerobe culture"
* $loinc#87936-1 "Bacteria identified in Burn by Anaerobe culture"
* $loinc#87941-1 "Bacteria identified in Placenta by Anaerobe culture"
* $loinc#87934-6 "Bacteria identified in Bile fluid by Anaerobe culture"
* $loinc#90273-4 "Bacteria identified in Catheter tip by Anaerobe culture"
* $loinc#88139-1 "Bacteria identified in Ocular fluid by Anaerobe culture"
* $loinc#87935-3 "Bacteria identified in Blood product unit by Anaerobe culture"
* $loinc#88683-8 "Bacteria identified in Bronchoalveolar lavage by Anaerobe culture"
* $loinc#87938-7 "Bacteria identified in Implanted device by Anaerobe culture"
* $loinc#87939-5 "Bacteria identified in Pericardial fluid by Anaerobe culture"
* $loinc#87940-3 "Bacteria identified in Peritoneal fluid by Anaerobe culture"
* $loinc#87942-9 "Bacteria identified in Pleural fluid by Anaerobe culture"
* $loinc#87933-8 "Bacteria identified in Amniotic fluid by Anaerobe culture"
* $loinc#87955-1 "Bacteria identified in Cord blood by Anaerobe culture"
* $loinc#87937-9 "Bacteria identified in Cerebral spinal fluid by Anaerobe culture"
* $loinc#598-3 "Bacteria identified in Aspirate by Anaerobe culture"
* $loinc#633-8 "Bacteria identified in Wound by Anaerobe culture"
* $loinc#87944-5 "Bacteria identified in Synovial fluid by Anaerobe culture"
* $loinc#17934-1 "Bacteria identified in Blood by Anaerobe culture"
* $loinc#91865-6 "Bacteria identified in Genital specimen by Anaerobe culture"
* $loinc#20878-5 "Bacteria identified in Isolate by Anaerobe culture"
* $loinc#91818-5 "Bacteria identified in Upper respiratory specimen by Anaerobe culture"
* $loinc#628-8 "Bacteria identified in Tissue by Anaerobe culture"
* $loinc#12281-2 "Bacteria identified in Cervix by Anaerobe culture"
* $loinc#17925-9 "Bacteria identified in Wound deep by Anaerobe culture"
* $loinc#89644-9 "Bacteria identified in Lower respiratory specimen by Anaerobe culture"
* $loinc#90276-7 "Bacteria identified in Semen by Anaerobe culture"
* $loinc#6461-8 "Bacteria identified in Stool by Anaerobe culture"
* $loinc#635-3 "Bacteria identified in Specimen by Anaerobe culture"
* $loinc#17935-8 "Bacteria # 2 identified in Blood by Anaerobe culture"
* $loinc#17923-4 "Bacteria # 2 identified in Tissue by Anaerobe culture"
* $loinc#17936-6 "Bacteria # 3 identified in Blood by Anaerobe culture"
* $loinc#17924-2 "Bacteria # 3 identified in Tissue by Anaerobe culture"
* $loinc#59051-3 "Bacteria # 4 identified in Tissue by Anaerobe culture"
* $loinc#17956-4 "Bacteria identified in Body fluid by Anaerobe culture"
* $loinc#90277-5 "Bacteria identified in Peritoneal dialysis fluid by Anaerobe culture"
* $loinc#91062-0 "Bacteria identified in Platelets from Blood product unit by Anaerobe culture"
* $loinc#17921-8 "Bacteria # 2 identified in Nose by Anaerobe culture"
* $loinc#17926-7 "Bacteria # 2 identified in Wound deep by Anaerobe culture"
* $loinc#44843-1 "Bacteria # 2 identified in Specimen by Anaerobe culture"
* $loinc#17922-6 "Bacteria # 3 identified in Nose by Anaerobe culture"
* $loinc#17927-5 "Bacteria # 3 identified in Wound deep by Anaerobe culture"
* $loinc#44853-0 "Bacteria # 3 identified in Specimen by Anaerobe culture"
* $loinc#44856-3 "Bacteria # 4 identified in Specimen by Anaerobe culture"
* $loinc#44857-1 "Bacteria # 5 identified in Specimen by Anaerobe culture"
* $loinc#44858-9 "Bacteria # 6 identified in Specimen by Anaerobe culture"
* $loinc#44859-7 "Bacteria # 7 identified in Specimen by Anaerobe culture"
* $loinc#17957-2 "Bacteria # 2 identified in Body fluid by Anaerobe culture"
* $loinc#17958-0 "Bacteria # 3 identified in Body fluid by Anaerobe culture"
* $loinc#43706-1 "Cytomegalovirus [Presence] in Anal by Shell vial culture"
* $loinc#43703-8 "Cytomegalovirus [Presence] in Blood by Shell vial culture"
* $loinc#43707-9 "Cytomegalovirus [Presence] in Tissue by Shell vial culture"
* $loinc#43700-4 "Cytomegalovirus [Presence] in Urine by Shell vial culture"
* $loinc#88622-6 "Cytomegalovirus [Presence] in Ocular fluid by Shell vial culture"
* $loinc#81328-7 "Cytomegalovirus [Presence] in Lower respiratory specimen by Shell vial culture"
* $loinc#43701-2 "Cytomegalovirus [Presence] in Specimen by Shell vial culture"
* $loinc#88624-2 "Cytomegalovirus [Presence] in Amniotic fluid by Shell vial culture"
* $loinc#43704-6 "Cytomegalovirus [Presence] in Body fluid by Shell vial culture"
* $loinc#43705-3 "Cytomegalovirus [Presence] in Bone marrow by Shell vial culture"
* $loinc#43702-0 "Cytomegalovirus [Presence] in Cerebral spinal fluid by Shell vial culture"
* $loinc#91866-4 "Bacteria identified in Mouth by Aerobe culture"
* $loinc#73960-7 "Bacteria identified in Mouth by Culture"
* $loinc#77193-1 "Bacteria identified in Uterus by Culture"
* $loinc#20694-6 "Bacteria identified in Embryo by Aerobe culture"
* $loinc#597-5 "Bacteria identified in Aspirate by Aerobe culture"
* $loinc#602-3 "Bacteria identified in Bone by Aerobe culture"
* $loinc#607-2 "Bacteria identified in Drain by Aerobe culture"
* $loinc#20693-8 "Bacteria identified in Litter by Aerobe culture"
* $loinc#20879-3 "Bacteria identified in Milk by Aerobe culture"
* $loinc#43426-6 "Bacteria identified in Nasopharynx by Aerobe culture"
* $loinc#87932-0 "Bacteria identified in Sinus by Aerobe culture"
* $loinc#632-0 "Bacteria identified in Wound by Aerobe culture"
* $loinc#78356-3 "Bacteria identified in Implanted device by Culture"
* $loinc#595-9 "Bacteria identified in Abscess by Aerobe culture"
* $loinc#17928-3 "Bacteria identified in Blood by Aerobe culture"
* $loinc#87930-4 "Bacteria identified in Burn by Aerobe culture"
* $loinc#605-6 "Bacteria identified in Cannula specimen by Aerobe culture"
* $loinc#608-0 "Bacteria identified in Ear by Aerobe culture"
* $loinc#32367-5 "Bacteria identified in Isolate by Aerobe culture"
* $loinc#14478-2 "Bacteria identified in Penis by Aerobe culture"
* $loinc#617-1 "Bacteria identified in Placenta by Aerobe culture"
* $loinc#91819-3 "Bacteria identified in Upper respiratory specimen by Aerobe culture"
* $loinc#620-5 "Bacteria identified in Skin by Aerobe culture"
* $loinc#17898-8 "Bacteria identified in Throat by Aerobe culture"
* $loinc#627-0 "Bacteria identified in Tissue by Aerobe culture"
* $loinc#14477-4 "Bacteria identified in Urethra by Aerobe culture"
* $loinc#76693-1 "Bacteria identified in Blood product unit.autologous by Culture"
* $loinc#599-1 "Bacteria identified in Blood product unit by Aerobe culture"
* $loinc#74355-9 "Bacteria identified in Bartholin cyst by Aerobe culture"
* $loinc#90270-0 "Bacteria identified in Bile fluid by Aerobe culture"
* $loinc#74348-4 "Bacteria identified in Bone from Donor by Aerobe culture"
* $loinc#604-9 "Bacteria identified in Bronchial specimen by Aerobe culture"
* $loinc#88142-5 "Bacteria identified in Cornea or Conjunctiva by Aerobe culture"
* $loinc#90274-2 "Bacteria identified in Catheter tip by Aerobe culture"
* $loinc#14475-8 "Bacteria identified in Cervix by Aerobe culture"
* $loinc#53617-7 "Bacteria identified in Duodenal fluid by Aerobe culture"
* $loinc#609-8 "Bacteria identified in Eye by Aerobe culture"
* $loinc#10352-3 "Bacteria identified in Genital specimen by Aerobe culture"
* $loinc#10353-1 "Bacteria identified in Nose by Aerobe culture"
* $loinc#88141-7 "Bacteria identified in Ocular fluid by Aerobe culture"
* $loinc#622-1 "Bacteria identified in Sputum by Aerobe culture"
* $loinc#631-2 "Bacteria identified in Unknown substance by Aerobe culture"
* $loinc#17909-3 "Bacteria identified in Wound deep by Aerobe culture"
* $loinc#17915-0 "Bacteria identified in Wound shallow by Aerobe culture"
* $loinc#17873-1 "Bacteria # 2 identified in Bone by Aerobe culture"
* $loinc#17874-9 "Bacteria # 3 identified in Bone by Aerobe culture"
* $loinc#17875-6 "Bacteria # 4 identified in Bone by Aerobe culture"
* $loinc#17876-4 "Bacteria # 5 identified in Bone by Aerobe culture"
* $loinc#17877-2 "Bacteria # 6 identified in Bone by Aerobe culture"
* $loinc#43411-8 "Bacteria identified in Aspirate by Culture"
* $loinc#60257-3 "Bacteria identified in Cornea by Culture"
* $loinc#43214-6 "Bacteria identified in Nasopharynx by Culture"
* $loinc#43307-8 "Bacteria identified in Sinus by Culture"
* $loinc#14093-9 "Bacteria identified in Water by Culture"
* $loinc#6608-4 "Virus identified in Isolate by Culture"
* $loinc#14459-2 "Virus identified in Penis by Culture"
* $loinc#43441-5 "Bacteria identified in Bronchoalveolar lavage by Aerobe culture"
* $loinc#43442-3 "Bacteria identified in Bronchial brush by Aerobe culture"
* $loinc#87931-2 "Bacteria identified in Implanted device by Aerobe culture"
* $loinc#90271-8 "Bacteria identified in Pericardial fluid by Aerobe culture"
* $loinc#90281-7 "Bacteria identified in Peritoneal fluid by Aerobe culture"
* $loinc#17279-1 "Bacteria identified in Pleural fluid by Aerobe culture"
* $loinc#89643-1 "Bacteria identified in Lower respiratory specimen by Aerobe culture"
* $loinc#90279-1 "Bacteria identified in Semen by Aerobe culture"
* $loinc#634-6 "Bacteria identified in Specimen by Aerobe culture"
* $loinc#17929-1 "Bacteria # 2 identified in Blood by Aerobe culture"
* $loinc#17899-6 "Bacteria # 2 identified in Throat by Aerobe culture"
* $loinc#17904-4 "Bacteria # 2 identified in Tissue by Aerobe culture"
* $loinc#17930-9 "Bacteria # 3 identified in Blood by Aerobe culture"
* $loinc#17900-2 "Bacteria # 3 identified in Throat by Aerobe culture"
* $loinc#17905-1 "Bacteria # 3 identified in Tissue by Aerobe culture"
* $loinc#17931-7 "Bacteria # 4 identified in Blood by Aerobe culture"
* $loinc#17890-5 "Bacteria # 4 identified in Nose by Aerobe culture"
* $loinc#17901-0 "Bacteria # 4 identified in Throat by Aerobe culture"
* $loinc#17906-9 "Bacteria # 4 identified in Tissue by Aerobe culture"
* $loinc#17932-5 "Bacteria # 5 identified in Blood by Aerobe culture"
* $loinc#17891-3 "Bacteria # 5 identified in Nose by Aerobe culture"
* $loinc#17902-8 "Bacteria # 5 identified in Throat by Aerobe culture"
* $loinc#17907-7 "Bacteria # 5 identified in Tissue by Aerobe culture"
* $loinc#17933-3 "Bacteria # 6 identified in Blood by Aerobe culture"
* $loinc#17892-1 "Bacteria # 6 identified in Nose by Aerobe culture"
* $loinc#17903-6 "Bacteria # 6 identified in Throat by Aerobe culture"
* $loinc#17908-5 "Bacteria # 6 identified in Tissue by Aerobe culture"
* $loinc#52966-9 "Bacteria identified in Anal by Culture"
* $loinc#600-7 "Bacteria identified in Blood by Culture"
* $loinc#603-1 "Bacteria identified in Burn by Culture"
* $loinc#6459-2 "Bacteria identified in Food by Culture"
* $loinc#43409-2 "Bacteria identified in Isolate by Culture"
* $loinc#626-2 "Bacteria identified in Throat by Culture"
* $loinc#43408-4 "Bacteria identified in Tissue by Culture"
* $loinc#10354-9 "Bacteria identified in Urethra by Culture"
* $loinc#630-4 "Bacteria identified in Urine by Culture"
* $loinc#6462-6 "Bacteria identified in Wound by Culture"
* $loinc#568-6 "Fungus identified in Aspirate by Culture"
* $loinc#571-0 "Fungus identified in Hair by Culture"
* $loinc#88687-9 "Fungus identified in Mouth by Culture"
* $loinc#87980-9 "Fungus identified in Sinus by Culture"
* $loinc#579-3 "Fungus identified in Wound by Culture"
* $loinc#5883-4 "Virus identified in Blood by Culture"
* $loinc#14454-3 "Virus identified in Nose by Culture"
* $loinc#72373-4 "Virus identified in Nasopharynx by Culture"
* $loinc#5885-9 "Virus identified in Skin by Culture"
* $loinc#5887-5 "Virus identified in Throat by Culture"
* $loinc#5888-3 "Virus identified in Tissue by Culture"
* $loinc#14460-0 "Virus identified in Urethra by Culture"
* $loinc#14457-6 "Virus identified in Urine by Culture"
* $loinc#87929-6 "Bacteria identified in Amniotic fluid by Aerobe culture"
* $loinc#87954-4 "Bacteria identified in Cord blood by Aerobe culture"
* $loinc#610-6 "Bacteria identified in Body fluid by Aerobe culture"
* $loinc#19126-2 "Bacteria identified in Bone marrow by Aerobe culture"
* $loinc#88236-5 "Bacteria identified in Cerebral spinal fluid by Aerobe culture"
* $loinc#90280-9 "Bacteria identified in Peritoneal dialysis fluid by Aerobe culture"
* $loinc#91063-8 "Bacteria identified in Platelets from Blood product unit by Aerobe culture"
* $loinc#90278-3 "Bacteria identified in Synovial fluid by Aerobe culture"
* $loinc#11261-5 "Bacteria identified in Vaginal fluid by Aerobe culture"
* $loinc#17878-0 "Bacteria # 2 identified in Bronchial specimen by Aerobe culture"
* $loinc#53614-4 "Bacteria # 2 identified in Duodenal fluid by Aerobe culture"
* $loinc#17883-0 "Bacteria # 2 identified in Genital specimen by Aerobe culture"
* $loinc#17888-9 "Bacteria # 2 identified in Nose by Aerobe culture"
* $loinc#17893-9 "Bacteria # 2 identified in Sputum by Aerobe culture"
* $loinc#17910-1 "Bacteria # 2 identified in Wound deep by Aerobe culture"
* $loinc#17916-8 "Bacteria # 2 identified in Wound shallow by Aerobe culture"
* $loinc#17879-8 "Bacteria # 3 identified in Bronchial specimen by Aerobe culture"
* $loinc#53615-1 "Bacteria # 3 identified in Duodenal fluid by Aerobe culture"
* $loinc#17884-8 "Bacteria # 3 identified in Genital specimen by Aerobe culture"
* $loinc#17889-7 "Bacteria # 3 identified in Nose by Aerobe culture"
* $loinc#17894-7 "Bacteria # 3 identified in Sputum by Aerobe culture"
* $loinc#17911-9 "Bacteria # 3 identified in Wound deep by Aerobe culture"
* $loinc#17917-6 "Bacteria # 3 identified in Wound shallow by Aerobe culture"
* $loinc#48567-2 "Bacteria # 3 identified in Specimen by Aerobe culture"
* $loinc#17880-6 "Bacteria # 4 identified in Bronchial specimen by Aerobe culture"
* $loinc#53616-9 "Bacteria # 4 identified in Duodenal fluid by Aerobe culture"
* $loinc#17885-5 "Bacteria # 4 identified in Genital specimen by Aerobe culture"
* $loinc#17895-4 "Bacteria # 4 identified in Sputum by Aerobe culture"
* $loinc#17912-7 "Bacteria # 4 identified in Wound deep by Aerobe culture"
* $loinc#17918-4 "Bacteria # 4 identified in Wound shallow by Aerobe culture"
* $loinc#17881-4 "Bacteria # 5 identified in Bronchial specimen by Aerobe culture"
* $loinc#17886-3 "Bacteria # 5 identified in Genital specimen by Aerobe culture"
* $loinc#17896-2 "Bacteria # 5 identified in Sputum by Aerobe culture"
* $loinc#17913-5 "Bacteria # 5 identified in Wound deep by Aerobe culture"
* $loinc#17919-2 "Bacteria # 5 identified in Wound shallow by Aerobe culture"
* $loinc#17882-2 "Bacteria # 6 identified in Bronchial specimen by Aerobe culture"
* $loinc#17887-1 "Bacteria # 6 identified in Genital specimen by Aerobe culture"
* $loinc#17897-0 "Bacteria # 6 identified in Sputum by Aerobe culture"
* $loinc#17914-3 "Bacteria # 6 identified in Wound deep by Aerobe culture"
* $loinc#17920-0 "Bacteria # 6 identified in Wound shallow by Aerobe culture"
* $loinc#47293-6 "Bacteria # 7 identified in Genital specimen by Aerobe culture"
* $loinc#47294-4 "Bacteria # 7 identified in Wound shallow by Aerobe culture"
* $loinc#48568-0 "Bacteria # 7 identified in Specimen by Aerobe culture"
* $loinc#47295-1 "Bacteria # 8 identified in Wound shallow by Aerobe culture"
* $loinc#48569-8 "Bacteria # 8 identified in Specimen by Aerobe culture"
* $loinc#13315-7 "Bacteria identified in 24 hour Urine by Culture"
* $loinc#68366-4 "Bacteria identified in Blood product unit by Culture"
* $loinc#53911-4 "Bacteria identified in Bile fluid by Culture"
* $loinc#56714-9 "Bacteria identified in Contact lens by Culture"
* $loinc#19128-8 "Bacteria identified in Catheter tip by Culture"
* $loinc#43410-0 "Bacteria identified in Cervix by Culture"
* $loinc#53908-0 "Bacteria identified in Esophageal brushing by Culture"
* $loinc#52967-7 "Bacteria identified in Gastric fluid by Culture"
* $loinc#6460-0 "Bacteria identified in Sputum by Culture"
* $loinc#58940-8 "Bacteria identified in Total parental nutrition by Culture"
* $loinc#74356-7 "Bacteria identified in Ventriculoperitoneal (VP) shunt by Culture"
* $loinc#17939-0 "Bacteria # 4 identified in Burn by Culture"
* $loinc#17940-8 "Bacteria # 5 identified in Burn by Culture"
* $loinc#17941-6 "Bacteria # 6 identified in Burn by Culture"
* $loinc#601-5 "Fungus identified in Blood by Culture"
* $loinc#87981-7 "Fungus identified in Burn by Culture"
* $loinc#15378-3 "Fungus identified in Isolate by Culture"
* $loinc#573-6 "Fungus identified in Nail by Culture"
* $loinc#91812-8 "Fungus identified in Upper respiratory specimen by Culture"
* $loinc#575-1 "Fungus identified in Skin by Culture"
* $loinc#578-5 "Fungus identified in Tissue by Culture"
* $loinc#40435-0 "Fungus identified in Urine by Culture"
* $loinc#14452-7 "Virus identified in Cervix by Culture"
* $loinc#14451-9 "Virus identified in Eye by Culture"
* $loinc#40480-6 "Virus identified in Genital specimen by Culture"
* $loinc#14456-8 "Virus identified in Peritoneal fluid by Culture"
* $loinc#6583-9 "Virus identified in Semen by Culture"
* $loinc#14458-4 "Virus identified in Sputum by Culture"
* $loinc#9822-8 "Bacteria identified in Dialysis fluid by Culture"
* $loinc#56715-6 "Bacteria identified in Pericardial fluid by Culture"
* $loinc#619-7 "Bacteria identified in Peritoneal fluid by Culture"
* $loinc#618-9 "Bacteria identified in Pleural fluid by Culture"
* $loinc#53558-3 "Bacteria identified in Semen by Culture"
* $loinc#43407-6 "Bacteria identified in Wound deep by Culture"
* $loinc#6463-4 "Bacteria identified in Specimen by Culture"
* $loinc#48727-2 "Bacteria # 2 identified in Blood by Culture"
* $loinc#17937-4 "Bacteria # 2 identified in Burn by Culture"
* $loinc#17970-5 "Bacteria # 2 identified in Urine by Culture"
* $loinc#48724-9 "Bacteria # 3 identified in Blood by Culture"
* $loinc#17938-2 "Bacteria # 3 identified in Burn by Culture"
* $loinc#17971-3 "Bacteria # 3 identified in Urine by Culture"
* $loinc#17972-1 "Bacteria # 4 identified in Urine by Culture"
* $loinc#17973-9 "Bacteria # 5 identified in Urine by Culture"
* $loinc#17974-7 "Bacteria # 6 identified in Urine by Culture"
* $loinc#44847-2 "Bacteria # 7 identified in Urine by Culture"
* $loinc#44849-8 "Bacteria # 8 identified in Urine by Culture"
* $loinc#45337-3 "Bacterial biochemical profile [Identifier] in Isolate by Culture"
* $loinc#24009-3 "Fungus identified in Bronchial specimen by Culture"
* $loinc#88143-3 "Fungus identified in Cornea or Conjunctiva by Culture"
* $loinc#41026-6 "Fungus identified in Genital specimen by Culture"
* $loinc#87976-7 "Fungus identified in Implanted device by Culture"
* $loinc#76073-6 "Fungus identified in Nose by Culture"
* $loinc#574-4 "Fungus identified in Peritoneal fluid by Culture"
* $loinc#89656-3 "Fungus identified in Lower respiratory specimen by Culture"
* $loinc#577-7 "Fungus identified in Sputum by Culture"
* $loinc#41446-6 "Parasite identified in Specimen by Culture"
* $loinc#10713-6 "Prototheca identified in Specimen by Culture"
* $loinc#14455-0 "Virus identified in Pleural fluid by Culture"
* $loinc#87709-2 "Virus identified in Lower respiratory specimen by Culture"
* $loinc#5886-7 "Virus identified in Stool by Culture"
* $loinc#6584-7 "Virus identified in Specimen by Culture"
* $loinc#17951-5 "Bacteria # 2 identified in Body fluid by Aerobe culture"
* $loinc#17952-3 "Bacteria # 3 identified in Body fluid by Aerobe culture"
* $loinc#17953-1 "Bacteria # 4 identified in Body fluid by Aerobe culture"
* $loinc#17954-9 "Bacteria # 5 identified in Body fluid by Aerobe culture"
* $loinc#17955-6 "Bacteria # 6 identified in Body fluid by Aerobe culture"
* $loinc#596-7 "Bacteria identified in Amniotic fluid by Culture"
* $loinc#60258-1 "Bacteria identified in Bone marrow by Culture"
* $loinc#60032-0 "Bacteria identified in Peritoneal dialysis fluid by Culture"
* $loinc#52973-5 "Bacteria identified in Sputum tracheal aspirate by Culture"
* $loinc#625-4 "Bacteria identified in Stool by Culture"
* $loinc#17961-4 "Bacteria # 4 identified in Peritoneal fluid by Culture"
* $loinc#17962-2 "Bacteria # 5 identified in Peritoneal fluid by Culture"
* $loinc#17963-0 "Bacteria # 6 identified in Peritoneal fluid by Culture"
* $loinc#88686-1 "Fungus identified in Bronchoalveolar lavage by Culture"
* $loinc#87977-5 "Fungus identified in Pericardial fluid by Culture"
* $loinc#87979-1 "Fungus identified in Pleural fluid by Culture"
* $loinc#27414-2 "Fungus identified in Stool by Culture"
* $loinc#580-1 "Fungus identified in Specimen by Culture"
* $loinc#11475-1 "Microorganism identified in Specimen by Culture"
* $loinc#11484-3 "Virus identified in Amniotic fluid by Culture"
* $loinc#40479-8 "Virus identified in Body fluid by Culture"
* $loinc#5884-2 "Virus identified in Cerebral spinal fluid by Culture"
* $loinc#72374-2 "Virus identified in Lung tissue by Culture"
* $loinc#14453-5 "Virus identified in Vaginal fluid by Culture"
* $loinc#611-4 "Bacteria identified in Body fluid by Culture"
* $loinc#606-4 "Bacteria identified in Cerebral spinal fluid by Culture"
* $loinc#17959-8 "Bacteria # 2 identified in Peritoneal fluid by Culture"
* $loinc#17964-8 "Bacteria # 2 identified in Stool by Culture"
* $loinc#44841-5 "Bacteria # 2 identified in Specimen by Culture"
* $loinc#17960-6 "Bacteria # 3 identified in Peritoneal fluid by Culture"
* $loinc#17965-5 "Bacteria # 3 identified in Stool by Culture"
* $loinc#44842-3 "Bacteria # 3 identified in Specimen by Culture"
* $loinc#17966-3 "Bacteria # 4 identified in Stool by Culture"
* $loinc#44844-9 "Bacteria # 4 identified in Specimen by Culture"
* $loinc#17967-1 "Bacteria # 5 identified in Stool by Culture"
* $loinc#44845-6 "Bacteria # 5 identified in Specimen by Culture"
* $loinc#17968-9 "Bacteria # 6 identified in Stool by Culture"
* $loinc#44846-4 "Bacteria # 6 identified in Specimen by Culture"
* $loinc#44848-0 "Bacteria # 7 identified in Specimen by Culture"
* $loinc#44850-6 "Bacteria # 8 identified in Specimen by Culture"
* $loinc#570-2 "Fungus identified in Body fluid by Culture"
* $loinc#572-8 "Fungus identified in Bone marrow by Culture"
* $loinc#569-4 "Fungus identified in Cerebral spinal fluid by Culture"
* $loinc#87978-3 "Fungus identified in Peritoneal dialysis fluid by Culture"
* $loinc#6409-7 "Fungus identified in Sputum tracheal aspirate by Culture"
* $loinc#97939-3 "Medium induced in vitro yeast conversion [Identifier] in Isolate by Culture"
* $loinc#17975-4 "Virus # 2 identified in Specimen by Culture"
* $loinc#17976-2 "Virus # 3 identified in Specimen by Culture"
* $loinc#621-3 "Bacteria identified in Synovial fluid by Culture"
* $loinc#576-9 "Fungus identified in Synovial fluid by Culture"
* $loinc#50766-5 "Fungus # 8 identified in Specimen by Culture"
* $loinc#17947-3 "Fungus # 2 identified in Specimen by Culture"
* $loinc#17948-1 "Fungus # 3 identified in Specimen by Culture"
* $loinc#17949-9 "Fungus # 4 identified in Specimen by Culture"
* $loinc#44840-7 "Fungus # 5 identified in Specimen by Culture"
* $loinc#47291-0 "Fungus # 6 identified in Specimen by Culture"
* $loinc#47292-8 "Fungus # 7 identified in Specimen by Culture"
* $loinc#78702-8 "Multiple drug resistant gram negative organism [Identifier] in Specimen by Culture"
* $loinc#90437-5 "Microorganism preliminary growth [Presence] in Blood by Anaerobe culture"
* $loinc#100910-9 "Gram negative bacteria.colistin resistant identified in Stool by Organism specific culture"
* $loinc#44093-3 "Neisseria meningitidis [Identifier] in Isolate by Organism specific culture"
* $loinc#90430-0 "Microorganism preliminary growth [Presence] in Body fluid by Anaerobe culture"
* $loinc#90073-8 "Lactobacillales identified in Isolate by Organism specific culture"
* $loinc#90067-0 "Enterobacteriaceae identified in Isolate by Organism specific culture"
* $loinc#91764-1 "Nocardia sp identified in Aspirate by Organism specific culture"
* $loinc#90078-7 "Yeast identified in Isolate by Organism specific culture"
* $loinc#90432-6 "Microorganism preliminary growth [Presence] in Platelets from Blood product unit by Anaerobe culture"
* $loinc#91773-2 "Herpes simplex virus identified in Aspirate by Organism specific culture"
* $loinc#88582-2 "Bordetella sp identified in Nasopharynx by Organism specific culture"
* $loinc#91872-2 "Bordetella sp identified in Throat by Organism specific culture"
* $loinc#90100-9 "Listeria sp identified in Isolate by Organism specific culture"
* $loinc#91770-8 "Enterovirus identified in Upper respiratory specimen by Organism specific culture"
* $loinc#90066-2 "Corynebacterium sp identified in Isolate by Organism specific culture"
* $loinc#6309-9 "Arbovirus identified in Blood by Organism specific culture"
* $loinc#6603-5 "Influenza virus identified in Throat by Organism specific culture"
* $loinc#6596-1 "Diphtheria identified in Isolate by Organism specific culture"
* $loinc#14482-4 "Diphtheria identified in Skin by Organism specific culture"
* $loinc#14479-0 "Diphtheria identified in Throat by Organism specific culture"
* $loinc#20964-3 "Shigella sp identified in Feed by Organism specific culture"
* $loinc#20968-4 "Staphylococcus sp identified in Cheese by Organism specific culture"
* $loinc#90076-1 "Staphylococcus sp identified in Isolate by Organism specific culture"
* $loinc#90077-9 "Urinary pathogens identified in Isolate by Organism specific culture"
* $loinc#6580-5 "Vibrio sp identified in Water by Organism specific culture"
* $loinc#53571-6 "Yeast identified in Genital specimen by Organism specific culture"
* $loinc#91779-9 "Yeast identified in Upper respiratory specimen by Organism specific culture"
* $loinc#90458-1 "Actinomyces sp identified in Aspirate by Organism specific culture"
* $loinc#88922-0 "Actinomyces sp identified in Tissue by Organism specific culture"
* $loinc#35417-5 "Herpes simplex virus identified in Anal by Organism specific culture"
* $loinc#35421-7 "Herpes simplex virus identified in Ear by Organism specific culture"
* $loinc#35451-4 "Herpes simplex virus identified in Nasopharynx by Organism specific culture"
* $loinc#35424-1 "Herpes simplex virus identified in Penis by Organism specific culture"
* $loinc#35425-8 "Herpes simplex virus identified in Placenta by Organism specific culture"
* $loinc#5858-6 "Herpes simplex virus identified in Skin by Organism specific culture"
* $loinc#35430-8 "Herpes simplex virus identified in Throat by Organism specific culture"
* $loinc#35431-6 "Herpes simplex virus identified in Tissue by Organism specific culture"
* $loinc#35433-2 "Herpes simplex virus identified in Urethra by Organism specific culture"
* $loinc#35432-4 "Herpes simplex virus identified in Urine by Organism specific culture"
* $loinc#35434-0 "Herpes simplex virus identified in Wound by Organism specific culture"
* $loinc#6429-5 "HIV identified in Blood by Organism specific culture"
* $loinc#91775-7 "Bordetella sp identified in Lower respiratory specimen by Organism specific culture"
* $loinc#91777-3 "Bordetella sp identified in Upper respiratory specimen by Organism specific culture"
* $loinc#20735-7 "Brucella sp identified in Milk by Organism specific culture"
* $loinc#20734-0 "Brucella sp identified in Tissue by Organism specific culture"
* $loinc#6330-5 "Campylobacter sp identified in Blood by Organism specific culture"
* $loinc#20738-1 "Campylobacter sp identified in Isolate by Organism specific culture"
* $loinc#20740-7 "Campylobacter sp identified in Tissue by Organism specific culture"
* $loinc#87956-9 "Legionella sp identified in Tissue by Organism specific culture"
* $loinc#38394-3 "Legionella sp identified in Urine by Organism specific culture"
* $loinc#87957-7 "Legionella sp identified in Water by Organism specific culture"
* $loinc#6453-5 "Leptospira sp identified in Blood by Organism specific culture"
* $loinc#23600-0 "Leptospira sp identified in Milk by Organism specific culture"
* $loinc#23599-4 "Leptospira sp identified in Tissue by Organism specific culture"
* $loinc#6455-0 "Leptospira sp identified in Urine by Organism specific culture"
* $loinc#45097-3 "Chlamydia sp identified in Anal by Organism specific culture"
* $loinc#45101-3 "Chlamydia sp identified in Nasopharynx by Organism specific culture"
* $loinc#558-7 "Chlamydia sp identified in Throat by Organism specific culture"
* $loinc#559-5 "Chlamydia sp identified in Urethra by Organism specific culture"
* $loinc#88200-1 "Influenza virus identified in Cornea or Conjunctiva by Organism specific culture"
* $loinc#91772-4 "Influenza virus identified in Upper respiratory specimen by Organism specific culture"
* $loinc#6536-7 "Rabies virus identified in Tissue by Organism specific culture"
* $loinc#14483-2 "Diphtheria identified in Bronchial specimen by Organism specific culture"
* $loinc#14481-6 "Diphtheria identified in Nose by Organism specific culture"
* $loinc#14480-8 "Diphtheria identified in Sputum by Organism specific culture"
* $loinc#88532-7 "Human metapneumovirus identified in Cornea or Conjunctiva by Organism specific culture"
* $loinc#91778-1 "Human metapneumovirus identified in Upper respiratory specimen by Organism specific culture"
* $loinc#10694-8 "Naegleria sp identified in Tissue by Organism specific culture"
* $loinc#43386-2 "Neisseria sp identified in Anal by Organism specific culture"
* $loinc#80369-2 "Neisseria sp identified in Anorectal by Organism specific culture"
* $loinc#43383-9 "Neisseria sp identified in Throat by Organism specific culture"
* $loinc#43384-7 "Neisseria sp identified in Urethra by Organism specific culture"
* $loinc#14226-5 "Nocardia sp identified in Isolate by Organism specific culture"
* $loinc#90075-3 "Non-Enterobacteriaceae identified in Isolate by Organism specific culture"
* $loinc#5878-4 "Rickettsia sp identified in Blood by Organism specific culture"
* $loinc#6548-2 "Rubella virus identified in Serum by Organism specific culture"
* $loinc#20952-8 "Salmonella sp identified in Egg by Organism specific culture"
* $loinc#20967-6 "Staphylococcus sp identified in Milk by Organism specific culture"
* $loinc#43389-6 "Streptococcus sp identified in Isolate by Organism specific culture"
* $loinc#20987-4 "Yersinia sp identified in Dairy product by Organism specific culture"
* $loinc#6578-9 "Vibrio sp identified in Blood by Organism specific culture"
* $loinc#89634-0 "Actinomyces sp identified in Implanted device by Organism specific culture"
* $loinc#6594-6 "Amoeba identified in Specimen by Organism specific culture"
* $loinc#35418-3 "Herpes simplex virus identified in Bronchial specimen by Organism specific culture"
* $loinc#88127-6 "Herpes simplex virus identified in Cornea or Conjunctiva by Organism specific culture"
* $loinc#35420-9 "Herpes simplex virus identified in Cervix by Organism specific culture"
* $loinc#32689-2 "Herpes simplex virus identified in Eye by Organism specific culture"
* $loinc#5856-0 "Herpes simplex virus identified in Genital specimen by Organism specific culture"
* $loinc#6430-3 "HIV identified in Semen by Organism specific culture"
* $loinc#6431-1 "HIV identified in Specimen by Organism specific culture"
* $loinc#87946-0 "Borrelia sp identified in Tissue by Organism specific culture"
* $loinc#551-2 "Brucella sp identified in Blood by Organism specific culture"
* $loinc#553-8 "Candida sp identified in Saliva (oral fluid) by Organism specific culture"
* $loinc#589-2 "Legionella sp identified in Bronchial specimen by Organism specific culture"
* $loinc#10687-2 "Leishmania sp identified in Tissue by Organism specific culture"
* $loinc#88537-6 "Enterovirus identified in Pericardial fluid by Organism specific culture"
* $loinc#5843-8 "Enterovirus identified in Specimen by Organism specific culture"
* $loinc#6406-3 "Flavivirus identified in Specimen by Organism specific culture"
* $loinc#73836-9 "Bacteria.fluoroquinolone resistant identified in Anal by Organism specific culture"
* $loinc#24005-1 "Chlamydia sp identified in Bronchial specimen by Organism specific culture"
* $loinc#556-1 "Chlamydia sp identified in Conjunctival specimen by Organism specific culture"
* $loinc#45098-1 "Chlamydia sp identified in Cervix by Organism specific culture"
* $loinc#557-9 "Chlamydia sp identified in Genital specimen by Organism specific culture"
* $loinc#6348-7 "Chlamydia sp identified in Sputum by Organism specific culture"
* $loinc#90068-8 "Gram negative bacilli identified in Isolate by Organism specific culture"
* $loinc#90069-6 "Gram positive bacilli identified in Isolate by Organism specific culture"
* $loinc#100905-9 "Gram positive bacteria identified in Isolate by Organism specific culture"
* $loinc#6310-7 "Arbovirus identified in Specimen by Organism specific culture"
* $loinc#6601-9 "Influenza virus identified in Sputum by Organism specific culture"
* $loinc#567-8 "Diphtheria identified in Specimen by Organism specific culture"
* $loinc#49110-0 "Mycoplasma sp identified in Urine by Organism specific culture"
* $loinc#43385-4 "Neisseria sp identified in Cervix by Organism specific culture"
* $loinc#89639-9 "Nocardia sp identified in Implanted device by Organism specific culture"
* $loinc#88531-9 "Parainfluenza virus identified in Cornea or Conjunctiva by Organism specific culture"
* $loinc#21442-9 "Parainfluenza virus identified in Nose by Organism specific culture"
* $loinc#53645-8 "Polio virus identified in Stool by Organism specific culture"
* $loinc#17530-7 "Retrovirus identified in Specimen by Organism specific culture"
* $loinc#6544-1 "Rickettsia sp identified in Genital specimen by Organism specific culture"
* $loinc#6545-8 "Rickettsia sp identified in Sputum by Organism specific culture"
* $loinc#20953-6 "Salmonella sp identified in Tissue by Organism specific culture"
* $loinc#87991-6 "Acanthamoeba sp identified in Contact lens by Organism specific culture"
* $loinc#88162-3 "Acanthamoeba sp identified in Cornea or Conjunctiva by Organism specific culture"
* $loinc#10635-1 "Acanthamoeba sp identified in Eye by Organism specific culture"
* $loinc#9781-6 "Acanthamoeba sp identified in Specimen by Organism specific culture"
* $loinc#90003-5 "Acinetobacter sp identified in Specimen by Organism specific culture"
* $loinc#29885-1 "Actinobacillus sp identified in Specimen by Organism specific culture"
* $loinc#89633-2 "Actinomyces sp identified in Lower respiratory specimen by Organism specific culture"
* $loinc#9816-0 "Actinomyces sp identified in Specimen by Organism specific culture"
* $loinc#10639-3 "Thermophilic Actinomycetes identified in Specimen by Organism specific culture"
* $loinc#9782-4 "Adenovirus sp identified in Specimen by Organism specific culture"
* $loinc#10643-5 "Amoeba identified in Stool by Organism specific culture"
* $loinc#69410-9 "Haemophilus influenzae [Identifier] in Specimen by Organism specific culture"
* $loinc#90072-0 "Haemophilus and Neisseria species identified in Isolate by Organism specific culture"
* $loinc#6600-1 "Haemophilus sp identified in Specimen by Organism specific culture"
* $loinc#35427-4 "Herpes simplex virus identified in Peritoneal fluid by Organism specific culture"
* $loinc#35426-6 "Herpes simplex virus identified in Pleural fluid by Organism specific culture"
* $loinc#88606-9 "Herpes simplex virus identified in Lower respiratory specimen by Organism specific culture"
* $loinc#35429-0 "Herpes simplex virus identified in Stool by Organism specific culture"
* $loinc#5859-4 "Herpes simplex virus identified in Specimen by Organism specific culture"
* $loinc#20445-3 "Herpes virus identified in Specimen by Organism specific culture"
* $loinc#6317-2 "Bordetella sp identified in Specimen by Organism specific culture"
* $loinc#6323-0 "Borrelia sp identified in Specimen by Organism specific culture"
* $loinc#24409-5 "Brachyspira sp identified in Specimen by Organism specific culture"
* $loinc#24003-6 "Brucella sp identified in Bone marrow by Organism specific culture"
* $loinc#23594-5 "Brucella sp identified in Semen by Organism specific culture"
* $loinc#552-0 "Brucella sp identified in Specimen by Organism specific culture"
* $loinc#88580-6 "Burkholderia sp identified in Lower respiratory specimen by Organism specific culture"
* $loinc#44798-7 "Burkholderia sp identified in Specimen by Organism specific culture"
* $loinc#20739-9 "Campylobacter sp identified in Body fluid by Organism specific culture"
* $loinc#6331-3 "Campylobacter sp identified in Stool by Organism specific culture"
* $loinc#6332-1 "Campylobacter sp identified in Specimen by Organism specific culture"
* $loinc#554-6 "Candida sp identified in Stool by Organism specific culture"
* $loinc#555-3 "Candida sp identified in Specimen by Organism specific culture"
* $loinc#38393-5 "Legionella sp identified in Pleural fluid by Organism specific culture"
* $loinc#88585-5 "Legionella sp identified in Lower respiratory specimen by Organism specific culture"
* $loinc#590-0 "Legionella sp identified in Sputum by Organism specific culture"
* $loinc#593-4 "Legionella sp identified in Specimen by Organism specific culture"
* $loinc#87987-4 "Leishmania sp identified in Blood by Organism specific culture"
* $loinc#51710-2 "Leishmania sp identified in Specimen by Organism specific culture"
* $loinc#594-2 "Leptospira sp identified in Specimen by Organism specific culture"
* $loinc#6609-2 "Listeria sp identified in Specimen by Organism specific culture"
* $loinc#48873-4 "Ehrlichia sp identified in Specimen by Organism specific culture"
* $loinc#100901-8 "Enterobacteriaceae.carbapenemase resistance phenotype [Identifier] in Anal by Organism specific culture"
* $loinc#100907-5 "Vancomycin resistant enterococcus [Identifier] in Specimen by Organism specific culture"
* $loinc#5839-6 "Enterovirus identified in Cerebral spinal fluid by Organism specific culture"
* $loinc#5842-0 "Enterovirus identified in Stool by Organism specific culture"
* $loinc#53955-1 "Escherichia coli O157 identified in Isolate by Organism specific culture"
* $loinc#38376-0 "Cryptococcus sp identified in Specimen by Organism specific culture"
* $loinc#27907-5 "Cryptosporidium sp [Identifier] in Stool by Organism specific culture"
* $loinc#20688-8 "Aspergillus sp identified in Litter by Organism specific culture"
* $loinc#38354-7 "Bartonella sp identified in Specimen by Organism specific culture"
* $loinc#45100-5 "Chlamydia sp identified in Vaginal fluid by Organism specific culture"
* $loinc#560-3 "Chlamydia sp identified in Specimen by Organism specific culture"
* $loinc#23601-8 "Mareks disease virus serotype [Identifier] in Tissue by Organism specific culture"
* $loinc#88568-1 "Influenza virus identified in Lower respiratory specimen by Organism specific culture"
* $loinc#6602-7 "Influenza virus identified in Sputum tracheal aspirate by Organism specific culture"
* $loinc#6604-3 "Influenza virus identified in Specimen by Organism specific culture"
* $loinc#6539-1 "Rabies virus identified in Specimen by Organism specific culture"
* $loinc#89652-2 "Human metapneumovirus identified in Lower respiratory specimen by Organism specific culture"
* $loinc#532-2 "Mycobacterium sp identified in Aspirate by Organism specific culture"
* $loinc#533-0 "Mycobacterium sp identified in Blood by Organism specific culture"
* $loinc#540-5 "Mycobacterium sp identified in Tissue by Organism specific culture"
* $loinc#541-3 "Mycobacterium sp identified in Urine by Organism specific culture"
* $loinc#542-1 "Mycobacterium sp identified in Wound by Organism specific culture"
* $loinc#14486-5 "Mycoplasma sp and Ureaplasma sp [Identifier] in Penis by Organism specific culture"
* $loinc#14487-3 "Mycoplasma sp and Ureaplasma sp [Identifier] in Urethra by Organism specific culture"
* $loinc#6486-5 "Mycoplasma sp identified in Specimen by Organism specific culture"
* $loinc#683-3 "Genital Mycoplasma identified in Genital specimen by Organism specific culture"
* $loinc#91776-5 "Respiratory Mycoplasma identified in Lower respiratory specimen by Organism specific culture"
* $loinc#684-1 "Respiratory Mycoplasma identified in Sputum by Organism specific culture"
* $loinc#685-8 "Respiratory Mycoplasma identified in Throat by Organism specific culture"
* $loinc#43387-0 "Neisseria sp identified in Specimen by Organism specific culture"
* $loinc#89638-1 "Nocardia sp identified in Lower respiratory specimen by Organism specific culture"
* $loinc#43365-6 "Nocardia sp identified in Specimen by Organism specific culture"
* $loinc#89653-0 "Parainfluenza virus identified in Lower respiratory specimen by Organism specific culture"
* $loinc#89654-8 "Parainfluenza virus identified in Upper respiratory specimen by Organism specific culture"
* $loinc#40436-8 "Parainfluenza virus identified in Specimen by Organism specific culture"
* $loinc#73907-8 "Polio virus identified in Specimen by Organism specific culture"
* $loinc#17520-8 "Respiratory syncytial virus identified in Specimen by Organism specific culture"
* $loinc#6546-6 "Rickettsia sp identified in Specimen by Organism specific culture"
* $loinc#6547-4 "Rotavirus identified in Specimen by Organism specific culture"
* $loinc#20955-1 "Salmonella sp identified in Stool by Organism specific culture"
* $loinc#17563-8 "Salmonella sp identified in Specimen by Organism specific culture"
* $loinc#10716-9 "Schistosoma sp identified in Specimen by Organism specific culture"
* $loinc#88586-3 "Shigella sp identified in Stool by Organism specific culture"
* $loinc#17576-0 "Shigella sp identified in Specimen by Organism specific culture"
* $loinc#20966-8 "Staphylococcus sp identified in Specimen by Organism specific culture"
* $loinc#38353-9 "Streptococcus sp identified in Specimen by Organism specific culture"
* $loinc#87995-7 "Strongyloides sp identified in Stool by Organism specific culture"
* $loinc#68458-9 "Trichomonas sp identified in Specimen by Organism specific culture"
* $loinc#10730-0 "Trypanosoma sp identified in Blood by Organism specific culture"
* $loinc#701-3 "Yersinia sp identified in Specimen by Organism specific culture"
* $loinc#32368-3 "Ureaplasma sp identified in Specimen by Organism specific culture"
* $loinc#6579-7 "Vibrio sp identified in Stool by Organism specific culture"
* $loinc#6581-3 "Vibrio sp identified in Specimen by Organism specific culture"
* $loinc#10728-4 "Trichomonas sp identified in Genital specimen by Organism specific culture"
* $loinc#28549-4 "Yersinia sp identified in Stool by Organism specific culture"
* $loinc#87990-8 "Acanthamoeba sp identified in Cerebral spinal fluid by Organism specific culture"
* $loinc#40684-3 "Acinetobacter sp multidrug resistant identified in Specimen by Organism specific culture"
* $loinc#35422-5 "Herpes simplex virus identified in Body fluid by Organism specific culture"
* $loinc#35419-1 "Herpes simplex virus identified in Cerebral spinal fluid by Organism specific culture"
* $loinc#35428-2 "Herpes simplex virus identified in Synovial fluid by Organism specific culture"
* $loinc#35423-3 "Herpes simplex virus identified in Vaginal fluid by Organism specific culture"
* $loinc#87945-2 "Borrelia sp identified in Cerebral spinal fluid by Organism specific culture"
* $loinc#87986-6 "Leishmania sp identified in Bone marrow by Organism specific culture"
* $loinc#6454-3 "Leptospira sp identified in Cerebral spinal fluid by Organism specific culture"
* $loinc#100902-6 "Enterobacteriaceae.carbapenemase resistance phenotype.OXA-48 [Identifier] in Anal by Organism specific culture"
* $loinc#13318-1 "Escherichia coli enteroinvasive identified in Stool by Organism specific culture"
* $loinc#16832-8 "Escherichia coli enterotoxic identified in Stool by Organism specific culture"
* $loinc#44089-1 "Escherichia coli O157:H7 [Identifier] in Specimen by Organism specific culture"
* $loinc#16836-9 "Escherichia coli verotoxic identified in Stool by Organism specific culture"
* $loinc#43979-4 "Aspergillus sp identified in Specimen by Organism specific culture"
* $loinc#73834-4 "Bacteria.carbapenem resistant identified in Anal by Organism specific culture"
* $loinc#73835-1 "Bacteria.extended spectrum beta lactamase resistance [Identifier] in Anal by Organism specific culture"
* $loinc#45099-9 "Chlamydia sp identified in Body fluid by Organism specific culture"
* $loinc#90070-4 "Gram positive catalase producing cocci identified in Isolate by Organism specific culture"
* $loinc#90071-2 "Gram positive non-catalase producing cocci identified in Isolate by Organism specific culture"
* $loinc#76687-3 "Mycobacterium sp identified in Bronchoalveolar lavage by Organism specific culture"
* $loinc#90284-1 "Mycobacterium sp identified in Bile fluid by Organism specific culture"
* $loinc#9823-6 "Mycobacterium sp identified in Bronchial specimen by Organism specific culture"
* $loinc#88167-2 "Mycobacterium sp identified in Cornea or Conjunctiva by Organism specific culture"
* $loinc#30045-9 "Mycobacterium sp identified in Dialysis fluid by Organism specific culture"
* $loinc#9824-4 "Mycobacterium sp identified in Gastric fluid by Organism specific culture"
* $loinc#89637-3 "Mycobacterium sp identified in Implanted device by Organism specific culture"
* $loinc#88168-0 "Mycobacterium sp identified in Ocular fluid by Organism specific culture"
* $loinc#537-1 "Mycobacterium sp identified in Peritoneal fluid by Organism specific culture"
* $loinc#53909-8 "Mycobacterium sp identified in Pleural fluid by Organism specific culture"
* $loinc#89636-5 "Mycobacterium sp identified in Lower respiratory specimen by Organism specific culture"
* $loinc#539-7 "Mycobacterium sp identified in Sputum by Organism specific culture"
* $loinc#543-9 "Mycobacterium sp identified in Specimen by Organism specific culture"
* $loinc#14484-0 "Mycoplasma sp and Ureaplasma sp [Identifier] in Cervix by Organism specific culture"
* $loinc#687-4 "Mycoplasma sp and Ureaplasma sp [Identifier] in Specimen by Organism specific culture"
* $loinc#686-6 "Respiratory Mycoplasma identified in Specimen by Organism specific culture"
* $loinc#43371-4 "Salmonella and Shigella sp identified in Stool by Organism specific culture"
* $loinc#42255-0 "Salmonella and Shigella sp identified in Specimen by Organism specific culture"
* $loinc#100899-4 "Enterobacteriaceae.extended spectrum beta lactamase resistance phenotype [Identifier] in Specimen by Organism specific culture"
* $loinc#94151-8 "Bacteria.carbapenem resistant identified in Specimen by Organism specific culture"
* $loinc#97758-7 "Fungus and Mycobacterium sp identified in Blood by Organism specific culture"
* $loinc#535-5 "Mycobacterium sp identified in Body fluid by Organism specific culture"
* $loinc#536-3 "Mycobacterium sp identified in Bone marrow by Organism specific culture"
* $loinc#534-8 "Mycobacterium sp identified in Cerebral spinal fluid by Organism specific culture"
* $loinc#538-9 "Mycobacterium sp identified in Synovial fluid by Organism specific culture"
* $loinc#44851-4 "Mycobacterium sp # 2 identified in Specimen by Organism specific culture"
* $loinc#44852-2 "Mycobacterium sp # 3 identified in Specimen by Organism specific culture"
* $loinc#44854-8 "Mycobacterium sp # 4 identified in Specimen by Organism specific culture"
* $loinc#44855-5 "Mycobacterium sp # 5 identified in Specimen by Organism specific culture"
* $loinc#14485-7 "Mycoplasma sp and Ureaplasma sp [Identifier] in Vaginal fluid by Organism specific culture"
* $loinc#90435-9 "Microorganism preliminary growth [Presence] in Blood by Aerobe culture"
* $loinc#87445-3 "Fungus [Presence] in Food by Culture"
* $loinc#16835-1 "Escherichia coli shiga-like toxin identified in Stool by Organism specific culture"
* $loinc#45335-7 "Bacteria Identification [Presence] in Isolate by Culture"
* $loinc#86319-1 "Staphylococcus aureus [Presence] in Food by Culture"
* $loinc#20762-1 "Clostridioides difficile [Presence] in Stool by Aerobe culture"
* $loinc#87241-6 "Bacillus atrophaeus [Presence] in Laboratory device by Culture"
* $loinc#87242-4 "Geobacillus stearothermophilus [Presence] in Laboratory device by Culture"
* $loinc#62454-4 "Herpes simplex virus and Varicella zoster virus identified in Specimen by Organism specific culture"
* $loinc#48806-4 "Salmonella sp+Shigella sp+Escherichia coli enterotoxic identified in Stool by Organism specific culture"
* $loinc#82302-1 "Campylobacter sp [Presence] in Stool by Culture"
* $loinc#82304-7 "Plesiomonas shigelloides [Presence] in Stool by Culture"
* $loinc#82301-3 "Salmonella sp [Presence] in Stool by Culture"
* $loinc#82300-5 "Shigella sp [Presence] in Stool by Culture"
* $loinc#82298-1 "Yersinia enterocolitica [Presence] in Specimen by Culture"
* $loinc#90429-2 "Microorganism preliminary growth [Presence] in Body fluid by Aerobe culture"
* $loinc#82303-9 "Escherichia coli O157 [Presence] in Stool by Culture"
* $loinc#90434-2 "Microorganism preliminary growth [Presence] in Platelets from Blood product unit by Aerobe culture"
* $loinc#88902-2 "Adenovirus [Presence] in Urine by Organism specific culture"
* $loinc#20871-0 "Listeria sp [Presence] in Cheese by Organism specific culture"
* $loinc#20870-2 "Listeria sp [Presence] in Milk by Organism specific culture"
* $loinc#100909-1 "Cronobacter sakazakii [Presence] by Organism specific culture"
* $loinc#18483-8 "Yeast [Presence] in Genital specimen by Organism specific culture"
* $loinc#88899-0 "Adenovirus [Presence] in Cornea or Conjunctiva by Organism specific culture"
* $loinc#43879-6 "Bordetella parapertussis [Presence] in Nasopharynx by Organism specific culture"
* $loinc#20869-4 "Leptospira sp [Presence] in Tissue by Organism specific culture"
* $loinc#87314-1 "Encephalomyocarditis virus [Presence] in Tissue by Organism specific culture"
* $loinc#33695-8 "Clostridium botulinum [Presence] in Isolate by Organism specific culture"
* $loinc#5836-2 "Cytomegalovirus [Presence] in Tissue by Organism specific culture"
* $loinc#5837-0 "Cytomegalovirus [Presence] in Urine by Organism specific culture"
* $loinc#91780-7 "Measles virus [Presence] in Lower respiratory specimen by Organism specific culture"
* $loinc#91786-4 "Measles virus [Presence] in Upper respiratory specimen by Organism specific culture"
* $loinc#91787-2 "Mumps virus [Presence] in Upper respiratory specimen by Organism specific culture"
* $loinc#20899-1 "Mycoplasma sp [Presence] in Exudate by Organism specific culture"
* $loinc#20898-3 "Mycoplasma sp [Presence] in Milk by Organism specific culture"
* $loinc#91781-5 "Neisseria gonorrhoeae [Presence] in Aspirate by Organism specific culture"
* $loinc#100908-3 "Pseudomonas aeruginosa [Presence] in Lower respiratory specimen by Organism specific culture"
* $loinc#91782-3 "Respiratory syncytial virus [Presence] in Lower respiratory specimen by Organism specific culture"
* $loinc#91785-6 "Respiratory syncytial virus [Presence] in Upper respiratory specimen by Organism specific culture"
* $loinc#89632-4 "Toxoplasma gondii [Presence] in Placenta by Organism specific culture"
* $loinc#14838-7 "Toxoplasma gondii [Presence] in Tissue by Organism specific culture"
* $loinc#55095-4 "Adenovirus [Presence] in Specimen by Organism specific culture"
* $loinc#91789-8 "Haemophilus ducreyi [Presence] in Genital specimen by Organism specific culture"
* $loinc#48741-3 "Bordetella pertussis [Presence] in Nasopharynx by Organism specific culture"
* $loinc#548-8 "Bordetella pertussis [Presence] in Throat by Organism specific culture"
* $loinc#100911-7 "Campylobacter sp [Presence] in Stool by Organism specific culture"
* $loinc#6595-3 "Klebsiella granulomatis [Presence] in Isolate by Organism specific culture"
* $loinc#86322-5 "Enterovirus [Presence] in Specimen by Organism specific culture"
* $loinc#33677-6 "Francisella tularensis [Presence] in Isolate by Organism specific culture"
* $loinc#97940-1 "Cryptococcus sp [Presence] in Isolate by Organism specific culture"
* $loinc#5835-4 "Cytomegalovirus [Presence] in Blood by Organism specific culture"
* $loinc#32675-1 "Cytomegalovirus [Presence] in Bronchial specimen by Organism specific culture"
* $loinc#91783-1 "Cytomegalovirus [Presence] in Lower respiratory specimen by Organism specific culture"
* $loinc#20860-3 "Infectious bronchitis virus [Presence] in Tissue by Organism specific culture"
* $loinc#51723-5 "Fungus [Presence] in Specimen by Organism specific culture"
* $loinc#13921-2 "Mumps virus [Presence] in Specimen by Organism specific culture"
* $loinc#14127-5 "Neisseria gonorrhoeae [Presence] in Anal by Organism specific culture"
* $loinc#80368-4 "Neisseria gonorrhoeae [Presence] in Anorectal by Organism specific culture"
* $loinc#690-8 "Neisseria gonorrhoeae [Presence] in Endometrium by Organism specific culture"
* $loinc#696-5 "Neisseria gonorrhoeae [Presence] in Throat by Organism specific culture"
* $loinc#697-3 "Neisseria gonorrhoeae [Presence] in Urethra by Organism specific culture"
* $loinc#88527-7 "Respiratory syncytial virus [Presence] in Cornea or Conjunctiva by Organism specific culture"
* $loinc#14129-1 "Respiratory syncytial virus [Presence] in Nose by Organism specific culture"
* $loinc#20962-7 "Serpulina hyodysenteria [Presence] in Spiral colon by Organism specific culture"
* $loinc#546-2 "Streptococcus.beta-hemolytic [Presence] in Throat by Organism specific culture"
* $loinc#23605-9 "Tritrichomonas foetus [Presence] in Placenta by Organism specific culture"
* $loinc#18482-0 "Yeast [Presence] in Specimen by Organism specific culture"
* $loinc#33686-7 "Yersinia pestis [Presence] in Isolate by Organism specific culture"
* $loinc#88898-2 "Adenovirus [Presence] in Lower respiratory specimen by Organism specific culture"
* $loinc#88900-6 "Adenovirus [Presence] in Upper respiratory specimen by Organism specific culture"
* $loinc#88901-4 "Adenovirus [Presence] in Stool by Organism specific culture"
* $loinc#30122-6 "Aeromonas sp [Presence] in Specimen by Organism specific culture"
* $loinc#11255-7 "Haemophilus ducreyi [Presence] in Specimen by Organism specific culture"
* $loinc#44015-6 "Helicobacter pylori [Presence] in Gastric fluid by Organism specific culture"
* $loinc#87953-6 "Helicobacter pylori [Presence] in Tissue by Organism specific culture"
* $loinc#44468-7 "Herpes simplex virus 1 [Presence] in Anal by Organism specific culture"
* $loinc#44464-6 "Herpes simplex virus 1 [Presence] in Skin by Organism specific culture"
* $loinc#44466-1 "Herpes simplex virus 1 [Presence] in Throat by Organism specific culture"
* $loinc#20702-7 "Bluetongue virus [Presence] in Specimen by Organism specific culture"
* $loinc#43925-7 "Bordetella parapertussis [Presence] in Specimen by Organism specific culture"
* $loinc#43896-0 "Bordetella pertussis [Presence] in Pleural fluid by Organism specific culture"
* $loinc#43890-3 "Bordetella pertussis [Presence] in Sputum by Organism specific culture"
* $loinc#549-6 "Bordetella pertussis [Presence] in Specimen by Organism specific culture"
* $loinc#16483-0 "Borrelia hermsii [Presence] in Specimen by Organism specific culture"
* $loinc#20716-7 "Bovine diarrhea virus [Presence] in Serum by Organism specific culture"
* $loinc#23593-7 "Bovine leukemia virus [Presence] in Blood by Organism specific culture"
* $loinc#44797-9 "Brucella sp [Presence] in Specimen by Organism specific culture"
* $loinc#70850-3 "Burkholderia mallei [Presence] in Specimen by Organism specific culture"
* $loinc#70851-1 "Burkholderia pseudomallei [Presence] in Specimen by Organism specific culture"
* $loinc#44800-1 "Burkholderia sp [Presence] in Specimen by Organism specific culture"
* $loinc#97513-6 "Campylobacter sp [Presence] in Specimen by Organism specific culture"
* $loinc#90002-7 "Candida auris [Presence] in Specimen by Organism specific culture"
* $loinc#59150-3 "Vancomycin resistant enterococcus [Presence] in Anal by Organism specific culture"
* $loinc#59151-1 "Vancomycin resistant enterococcus [Presence] in Urine by Organism specific culture"
* $loinc#20807-4 "Equine arteritis virus [Presence] in Blood by Organism specific culture"
* $loinc#96356-1 "Equine herpesvirus 3 [Presence] in Specimen by Organism specific culture"
* $loinc#96357-9 "Equine herpesvirus 4 [Presence] in Specimen by Organism specific culture"
* $loinc#86724-2 "Erysipelothrix rhusiopathiae [Presence] in Specimen by Organism specific culture"
* $loinc#33676-8 "Francisella tularensis [Presence] in Specimen by Organism specific culture"
* $loinc#562-9 "Clostridioides difficile [Presence] in Stool by Organism specific culture"
* $loinc#563-7 "Clostridioides difficile [Presence] in Specimen by Organism specific culture"
* $loinc#87948-6 "Clostridium botulinum [Presence] in Stool by Organism specific culture"
* $loinc#33694-1 "Clostridium botulinum [Presence] in Specimen by Organism specific culture"
* $loinc#77496-8 "Clostridium perfringens [Presence] in Specimen by Organism specific culture"
* $loinc#88584-8 "Corynebacterium diphtheriae [Presence] in Upper respiratory specimen by Organism specific culture"
* $loinc#16676-9 "Corynebacterium diphtheriae [Presence] in Specimen by Organism specific culture"
* $loinc#88625-9 "Cytomegalovirus [Presence] in Ocular fluid by Organism specific culture"
* $loinc#5838-8 "Cytomegalovirus [Presence] in Specimen by Organism specific culture"
* $loinc#37982-6 "Avian paramyxovirus [Presence] in Specimen by Organism specific culture"
* $loinc#77495-0 "Bacillus cereus [Presence] in Specimen by Organism specific culture"
* $loinc#45096-5 "Chlamydia trachomatis [Presence] in Nasopharynx by Organism specific culture"
* $loinc#21284-5 "Gardnerella vaginalis [Presence] in Genital specimen by Organism specific culture"
* $loinc#90275-9 "Gardnerella vaginalis [Presence] in Vaginal fluid by Organism specific culture"
* $loinc#76626-1 "Measles virus [Presence] in Specimen by Organism specific culture"
* $loinc#64412-0 "Mycobacterium sp [Presence] in Blood by Organism specific culture"
* $loinc#20902-3 "Mycoplasma sp+Ureaplasma sp [Presence] in Tissue by Organism specific culture"
* $loinc#97529-2 "Naegleria fowleri [Presence] in Specimen by Organism specific culture"
* $loinc#30099-6 "Neisseria gonorrhoeae [Presence] in Conjunctival specimen by Organism specific culture"
* $loinc#688-2 "Neisseria gonorrhoeae [Presence] in Cervix by Organism specific culture"
* $loinc#691-6 "Neisseria gonorrhoeae [Presence] in Genital specimen by Organism specific culture"
* $loinc#694-0 "Neisseria gonorrhoeae [Presence] in Semen by Organism specific culture"
* $loinc#698-1 "Neisseria gonorrhoeae [Presence] in Specimen by Organism specific culture"
* $loinc#91788-0 "Neisseria meningitidis [Presence] in Upper respiratory specimen by Organism specific culture"
* $loinc#87958-5 "Neisseria meningitidis [Presence] in Throat by Organism specific culture"
* $loinc#48874-2 "Neorickettsia sp [Presence] in Specimen by Organism specific culture"
* $loinc#86204-5 "Porcine deltacoronavirus [Presence] in Specimen by Organism specific culture"
* $loinc#87388-5 "Porcine sapelovirus [Presence] in Specimen by Organism specific culture"
* $loinc#87399-2 "Porcine teschovirus [Presence] in Specimen by Organism specific culture"
* $loinc#55100-2 "Respiratory syncytial virus [Presence] in Specimen by Organism specific culture"
* $loinc#86689-7 "Rotavirus A [Presence] in Specimen by Organism specific culture"
* $loinc#86688-9 "Rotavirus C [Presence] in Specimen by Organism specific culture"
* $loinc#34891-2 "Salmonella enteritidis [Presence] in Specimen by Organism specific culture"
* $loinc#87345-5 "Senecavirus A [Presence] in Specimen by Organism specific culture"
* $loinc#20963-5 "Serpulina hyodysenteria [Presence] in Stool by Organism specific culture"
* $loinc#46454-5 "Shigella sp [Presence] in Specimen by Organism specific culture"
* $loinc#100897-8 "Staphylococcus aureus [Presence] in Specimen by Organism specific culture"
* $loinc#76081-9 "Methicillin resistant Staphylococcus aureus [Presence] in Pharynx by Organism specific culture"
* $loinc#11267-2 "Streptococcus.beta-hemolytic [Presence] in Genital specimen by Organism specific culture"
* $loinc#547-0 "Streptococcus.beta-hemolytic [Presence] in Specimen by Organism specific culture"
* $loinc#23603-4 "Taylorella equigenitalis [Presence] in Genital specimen by Organism specific culture"
* $loinc#88161-5 "Toxoplasma gondii [Presence] in Ocular fluid by Organism specific culture"
* $loinc#91790-6 "Trichomonas vaginalis [Presence] in Genital specimen by Organism specific culture"
* $loinc#20976-7 "Tritrichomonas foetus [Presence] in Preputial wash by Organism specific culture"
* $loinc#33685-9 "Yersinia pestis [Presence] in Specimen by Organism specific culture"
* $loinc#17852-5 "Ureaplasma urealyticum [Presence] in Specimen by Organism specific culture"
* $loinc#48872-6 "Anaplasma phagocytophilum [Presence] in Specimen by Organism specific culture"
* $loinc#87952-8 "Helicobacter pylori [Presence] in Stool by Organism specific culture"
* $loinc#587-6 "Helicobacter pylori [Presence] in Specimen by Organism specific culture"
* $loinc#44467-9 "Herpes simplex virus 1 [Presence] in Cervix by Organism specific culture"
* $loinc#44465-3 "Herpes simplex virus 1 [Presence] in Genital specimen by Organism specific culture"
* $loinc#16291-7 "Herpes simplex virus 1 [Presence] in Specimen by Organism specific culture"
* $loinc#44490-1 "Herpes simplex virus 2 [Presence] in Anal by Organism specific culture"
* $loinc#44489-3 "Herpes simplex virus 2 [Presence] in Cervix by Organism specific culture"
* $loinc#44487-7 "Herpes simplex virus 2 [Presence] in Genital specimen by Organism specific culture"
* $loinc#44486-9 "Herpes simplex virus 2 [Presence] in Skin by Organism specific culture"
* $loinc#44488-5 "Herpes simplex virus 2 [Presence] in Throat by Organism specific culture"
* $loinc#11550-1 "Borrelia burgdorferi [Presence] in Specimen by Organism specific culture"
* $loinc#94620-2 "Bovine diarrhea virus [Presence] in Specimen by Organism specific culture"
* $loinc#94618-6 "Bovine respiratory syncytial virus [Presence] in Specimen by Organism specific culture"
* $loinc#77924-9 "Enterobacteriaceae.carbapenem resistant [Presence] in Anorectal or stool specimen by Organism specific culture"
* $loinc#13316-5 "Vancomycin resistant enterococcus [Presence] in Specimen by Organism specific culture"
* $loinc#94600-4 "Equine influenza virus [Presence] in Specimen by Organism specific culture"
* $loinc#44090-9 "Escherichia coli O157:H7 [Presence] in Isolate by Organism specific culture"
* $loinc#20823-1 "Escherichia coli O157:H7 [Presence] in Raw milk by Organism specific culture"
* $loinc#44799-5 "Coxiella burnetii [Presence] in Specimen by Organism specific culture"
* $loinc#38377-8 "Cryptococcus neoformans [Presence] in Specimen by Organism specific culture"
* $loinc#34201-4 "Cytomegalovirus [Presence] in Amniotic fluid by Organism specific culture"
* $loinc#88564-0 "Cytomegalovirus [Presence] in Bone marrow by Organism specific culture"
* $loinc#88623-4 "Cytomegalovirus [Presence] in Cerebral spinal fluid by Organism specific culture"
* $loinc#11469-4 "Bacillus anthracis [Presence] in Specimen by Organism specific culture"
* $loinc#45093-2 "Chlamydia trachomatis [Presence] in Anal by Organism specific culture"
* $loinc#80367-6 "Chlamydia trachomatis [Presence] in Anorectal by Organism specific culture"
* $loinc#14461-8 "Chlamydia trachomatis [Presence] in Blood by Organism specific culture"
* $loinc#45094-0 "Chlamydia trachomatis [Presence] in Conjunctival specimen by Organism specific culture"
* $loinc#14463-4 "Chlamydia trachomatis [Presence] in Cervix by Organism specific culture"
* $loinc#45095-7 "Chlamydia trachomatis [Presence] in Genital specimen by Organism specific culture"
* $loinc#89648-0 "Chlamydia trachomatis [Presence] in Throat by Organism specific culture"
* $loinc#87950-2 "Chlamydia trachomatis [Presence] in Tissue by Organism specific culture"
* $loinc#14465-9 "Chlamydia trachomatis [Presence] in Urethra by Organism specific culture"
* $loinc#10670-8 "Giardia lamblia [Presence] in Stool by Organism specific culture"
* $loinc#48310-7 "Influenza virus A [Presence] in Specimen by Organism specific culture"
* $loinc#38382-8 "Influenza virus B [Presence] in Specimen by Organism specific culture"
* $loinc#90438-3 "Mycobacterium preliminary growth [Presence] in Tissue by Organism specific culture"
* $loinc#50941-4 "Mycobacterium sp [Presence] in Specimen by Organism specific culture"
* $loinc#15388-2 "Mycoplasma hominis [Presence] in Specimen by Organism specific culture"
* $loinc#692-4 "Neisseria gonorrhoeae [Presence] in Genital lochia by Organism specific culture"
* $loinc#693-2 "Neisseria gonorrhoeae [Presence] in Vaginal fluid by Organism specific culture"
* $loinc#16134-9 "Neisseria meningitidis [Presence] in Specimen by Organism specific culture"
* $loinc#87324-0 "Porcine circovirus type 2 [Presence] in Specimen by Organism specific culture"
* $loinc#86200-3 "Porcine epidemic diarrhea virus [Presence] in Specimen by Organism specific culture"
* $loinc#86733-3 "Porcine parvovirus [Presence] in Specimen by Organism specific culture"
* $loinc#63480-8 "Pseudomonas aeruginosa.multidrug resistant isolate [Presence] in Specimen by Organism specific culture"
* $loinc#23602-6 "Salmonella enteritidis [Presence] in Stool by Organism specific culture"
* $loinc#53572-4 "Methicillin resistant Staphylococcus aureus [Presence] in Genital specimen by Organism specific culture"
* $loinc#52969-3 "Methicillin resistant Staphylococcus aureus [Presence] in Nose by Organism specific culture"
* $loinc#11268-0 "Streptococcus pyogenes [Presence] in Throat by Organism specific culture"
* $loinc#90301-3 "Toxoplasma gondii [Presence] in Amniotic fluid by Organism specific culture"
* $loinc#87982-5 "Toxoplasma gondii [Presence] in Bone marrow by Organism specific culture"
* $loinc#89599-5 "Toxoplasma gondii [Presence] in Cerebral spinal fluid by Organism specific culture"
* $loinc#90285-8 "Trichomonas vaginalis [Presence] in Vaginal fluid by Organism specific culture"
* $loinc#23604-2 "Tritrichomonas foetus [Presence] in Body fluid by Organism specific culture"
* $loinc#23606-7 "Tritrichomonas foetus [Presence] in Genital fluid by Organism specific culture"
* $loinc#88135-9 "Varicella zoster virus [Presence] in Cornea or Conjunctiva by Organism specific culture"
* $loinc#88136-7 "Varicella zoster virus [Presence] in Ocular fluid by Organism specific culture"
* $loinc#91784-9 "Varicella zoster virus [Presence] in Lower respiratory specimen by Organism specific culture"
* $loinc#44463-8 "Herpes simplex virus 1 [Presence] in Vaginal fluid by Organism specific culture"
* $loinc#44485-1 "Herpes simplex virus 2 [Presence] in Vaginal fluid by Organism specific culture"
* $loinc#44484-4 "Herpes simplex virus 2 [Presence] in Specimen by Organism specific culture"
* $loinc#94619-4 "Bovine herpesvirus 1 [Presence] in Specimen by Organism specific culture"
* $loinc#96358-7 "Bovine parainfluenza virus 3 [Presence] in Specimen by Organism specific culture"
* $loinc#96355-3 "Equine herpesvirus 1 [Presence] in Specimen by Organism specific culture"
* $loinc#10851-4 "Escherichia coli O157:H7 [Presence] in Stool by Organism specific culture"
* $loinc#14462-6 "Chlamydia trachomatis [Presence] in Cerebral spinal fluid by Organism specific culture"
* $loinc#14467-5 "Chlamydia trachomatis [Presence] in Urine sediment by Organism specific culture"
* $loinc#14464-2 "Chlamydia trachomatis [Presence] in Vaginal fluid by Organism specific culture"
* $loinc#6349-5 "Chlamydia trachomatis [Presence] in Specimen by Organism specific culture"
* $loinc#21184-7 "Chlamydophila pneumoniae [Presence] in Specimen by Organism specific culture"
* $loinc#59065-3 "Chlamydophila psittaci [Presence] in Bronchial brush by Organism specific culture"
* $loinc#20752-2 "Chlamydophila psittaci [Presence] in Specimen by Organism specific culture"
* $loinc#90436-7 "Microorganism preliminary growth [Presence] in Body fluid by Organism specific culture"
* $loinc#20892-6 "Mycobacterium avium ss paratuberculosis [Presence] in Tissue by Organism specific culture"
* $loinc#91590-0 "Mycobacterium preliminary growth [Presence] in Body fluid by Organism specific culture"
* $loinc#90433-4 "Mycobacterium preliminary growth [Presence] in Sputum by Organism specific culture"
* $loinc#19054-6 "Mycoplasma pneumoniae [Presence] in Specimen by Organism specific culture"
* $loinc#695-7 "Neisseria gonorrhoeae [Presence] in Synovial fluid by Organism specific culture"
* $loinc#86581-6 "Neisseria meningitidis [Presence] in Cerebral spinal fluid by Organism specific culture"
* $loinc#48875-9 "Orientia tsutsugamushi [Presence] in Specimen by Organism specific culture"
* $loinc#55097-0 "Parainfluenza virus 1 [Presence] in Specimen by Organism specific culture"
* $loinc#55098-8 "Parainfluenza virus 2 [Presence] in Specimen by Organism specific culture"
* $loinc#55099-6 "Parainfluenza virus 3 [Presence] in Specimen by Organism specific culture"
* $loinc#87341-4 "Pseudorabies virus [Presence] in Specimen by Organism specific culture"
* $loinc#13317-3 "Methicillin resistant Staphylococcus aureus [Presence] in Specimen by Organism specific culture"
* $loinc#52968-5 "Streptococcus agalactiae [Presence] in Anal by Organism specific culture"
* $loinc#581-9 "Streptococcus agalactiae [Presence] in Cervix by Organism specific culture"
* $loinc#582-7 "Streptococcus agalactiae [Presence] in Genital specimen by Organism specific culture"
* $loinc#585-0 "Streptococcus agalactiae [Presence] in Throat by Organism specific culture"
* $loinc#17656-0 "Streptococcus pyogenes [Presence] in Specimen by Organism specific culture"
* $loinc#81316-2 "Trichomonas vaginalis [Presence] in Urine sediment by Organism specific culture"
* $loinc#10860-5 "Varicella zoster virus [Presence] in Specimen by Organism specific culture"
* $loinc#24427-7 "Mycobacterium avium ss paratuberculosis [Presence] in Specimen by Organism specific culture"
* $loinc#94763-0 "SARS-CoV-2 (COVID-19) [Presence] in Specimen by Organism specific culture"
* $loinc#583-5 "Streptococcus agalactiae [Presence] in Genital lochia by Organism specific culture"
* $loinc#584-3 "Streptococcus agalactiae [Presence] in Vaginal fluid by Organism specific culture"
* $loinc#72607-5 "Streptococcus agalactiae [Presence] in Vag+Rectum by Organism specific culture"
* $loinc#586-8 "Streptococcus agalactiae [Presence] in Specimen by Organism specific culture"
* $loinc#20893-4 "Mycobacterium avium ss paratuberculosis [Presence] in Stool by Organism specific culture"
* $loinc#74312-0 "PRRSV [Presence] in Specimen by Organism specific culture"