canonical: https://www.medizininformatik-initiative.de/fhir/modul-mikrobio
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
status: active
version: 2025.0.0
dependencies:
  de.medizininformatikinitiative.kerndatensatz.laborbefund: 2025.0.2
  de.medizininformatikinitiative.kerndatensatz.meta: 2025.0.2
