Logical: MII_LM_Mikrobio_Logical_Model
Parent: Element
Id: mii-lm-mikrobio-logical-model
Title: "MII LM Mikrobio Logical Model"
Description: "Logical Model für die grafische Darstellung des jeweiligen Art-Decor-Modells [DE]"
* insert PR_CS_VS_Version
* insert Publisher
* ^url = "https://www.medizininformatik-initiative.de/fhir/modul-mikrobio/StructureDefinition/mii-lm-mikrobio-logical-model-de"
* ^type = "https://www.medizininformatik-initiative.de/fhir/modul-mikrobio/StructureDefinition/mii-lm-mikrobio-logical-model"
* . ^short = "mii lm mikrobio logical model"
* KulturDiagnostik 0..* BackboneElement "Kultur Diagnostik" "Kultur Diagnostik"
  * Nachweis 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Erreger Nachweis" "Erreger Nachweis"
  * Erregername 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Erregername" "Erregername"
  * KulturMethode 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Kultur Methode" "Kultur Methode"
  * MRGN 0..* BackboneElement "Multiresistente gramnegative Bakterien Klassifikation" "Multiresistente gramnegative Bakterien Klassifikation"
  * Keimzahl 0..* BackboneElement "Keimzahl" "Keimzahl"
  * Resistenz 0..* BackboneElement "Bestimmung der Resistenz" "Bestimmung der Resistenz"
* Mikroskopie 0..* BackboneElement "Mikroskopische Untersuchung" "Mikroskopische Untersuchung"
  * Nachweis 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Erreger Nachweis" "Erreger Nachweis"
  * Erregername 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Erregername" "Erregername"
  * SemiquantitativesErgebnis 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "SemiquantitativesErgebnis" "SemiquantitativesErgebnis"
  * QuantitativesErgebnis 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Quantitatives Ergebnis" "Quantitatives Ergebnis"
  * Methode 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Mikroskopische Methode" "Mikroskopische Methode"
  * Morphologie 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Morphologie" "Morphologie"
  * BarlettScore 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Barlett score" "Barlett score"
  * NugentScore 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Nugent score" "Nugent score"
* MolekularDiagnostik 0..* BackboneElement "Molekulare Diagnostik" "Molekulare Diagnostik"
  * Nachweis 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Erregernachweis" "Erregernachweis"
  * Erregername 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Erregername" "Erregername"
  * PCRQuantitativesErgebnis 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "PCR Quantitatives Ergebnis" "PCR Quantitatives Ergebnis"
  * CycleThreshold 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Cycle threshold" "Cycle threshold"
* SerologieImmunologie 0..* BackboneElement "Serologie und Immunologie" "Serologie und Immunologie"
  * QuantitativesErgebnisAntigenTest 0..* http://hl7.org/fhir/StructureDefinition/Quantity "Quantitatives Ergebnis (Antigen Test)" "Quantitatives Ergebnis (Antigen Test)"
  * QualitativesErgebnisAntigenTest 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Qualitatives Ergebnis (Antigen Test)" "Qualitatives Ergebnis (Antigen Test)"
  * QuantitativesErgebnisSerologie 0..* http://hl7.org/fhir/StructureDefinition/Quantity "Quantitatives Ergebnis des serologischen Tests" "Quantitatives Ergebnis des serologischen Tests"
  * QualitativesErgebnisSerologie 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Qualitatives Ergebnis des serologischen Tests" "Qualitatives Ergebnis des serologischen Tests"
  * Aviditaet 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Avidität" "Avidität"
* WeitereEigenschaftenOrganismus 0..* BackboneElement "Weitere Eigenschaften des Organismus" "Weitere Eigenschaften des Organismus"
  * MREKlasse 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Multiresistente Erreger Klasse" "Multiresistente Erreger Klasse"
  * MRGNKlasse 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "MRGN Klasse" "MRGN Klasse"
  * Virulenzfaktor 0..* BackboneElement "Virulenzfaktor" "Virulenzfaktor"
  * Resistanzmechanism 0..* BackboneElement "Resistanzmechanism" "Resistanzmechanism"
    * ResistenzGene 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Resistenz Gene" "Resistenz Gene"
    * ResistenzMutation 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Resistenz Mutation" "Resistenz Mutation"
  * VoraussichtlicheEmpfindlichkeit 0..* http://hl7.org/fhir/StructureDefinition/CodeableConcept "Voraussichtliche Empfindlichkeit" "Voraussichtliche Empfindlichkeit"
* MikrobiologieBericht 0..* BackboneElement "Mikrobiologie Bericht" "Mikrobiologie Bericht"