// Fachliche Ausprägungen der mikrobiologischen Untersuchung.
// Erbt über Parent die gemeinsamen Angaben aus MII_LM_Mikrobio_Untersuchung; hier stehen ausschließlich
// die Attribute, die das jeweilige Profil selbst festlegt (code, value[x], method, interpretation, derivedFrom).
Logical: MII_LM_Mikrobio_Untersuchungsarten
Parent: MII_LM_Mikrobio_Untersuchung
Id: mii-lm-mikrobio-untersuchungsarten
Title: "MII LM Mikrobio Untersuchungsarten"
Description: "Fachliche Ausprägungen der mikrobiologischen Untersuchung für die grafische Darstellung des Mikrobiologie-Datenmodells 2027 [DE]"
* insert PR_CS_VS_Version
* insert Publisher
* . ^short = "Mikrobiologische Untersuchungsarten"
* . ^definition = "Die fachlichen Ausprägungen einer mikrobiologischen Untersuchung. Jede Ausprägung ergänzt die von MII_LM_Mikrobio_Untersuchung geerbten gemeinsamen Angaben um ihre spezifischen Attribute."

// Kultur
* Kultur 0..* BackboneElement "Kultur" "Kulturbasierte und mikroskopische Untersuchungen sowie die daran anschließende Empfindlichkeitstestung."
  * AllgemeineKultur 0..* BackboneElement "Allgemeine Kultur" "Ergebnis einer nicht zielgerichteten mikrobiologischen Kultur, die prüft, ob in der Probe irgendein Mikroorganismus wächst."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung der Untersuchung; hier fest: Nachweis eines Mikroorganismus mittels Kultur (LOINC)."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "Wachstum oder kein Wachstum in der Probe (SNOMED CT). Ein unbestimmbares Ergebnis wird nicht hier, sondern über den Grund für fehlende Daten abgebildet."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes Kulturverfahren (SNOMED CT)."
  * SpezifischeKultur 0..* BackboneElement "Spezifische Kultur" "Ergebnis einer zielgerichteten mikrobiologischen Kultur, die prüft, ob ein vordefinierter Mikroorganismus in der Probe wächst."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung des gesuchten Mikroorganismus und des Kulturverfahrens (LOINC)."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "Wachstum oder kein Wachstum des gesuchten Mikroorganismus (SNOMED CT). Ein unbestimmbares Ergebnis wird nicht hier, sondern über den Grund für fehlende Daten abgebildet."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes Kulturverfahren (SNOMED CT)."
  * Mikroskopie 0..* BackboneElement "Mikroskopie" "Morphologische Beobachtung von Mikroorganismen mittels mikroskopischer Untersuchung, ohne taxonomische Identifikation."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung der Untersuchung; mikroskopische Beobachtung (LOINC)."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "Beobachtete Morphologie (SNOMED CT)."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes mikroskopisches Verfahren einschließlich Färbetechnik, z. B. Gramfärbung (SNOMED CT)."
  * BarlettScore 0..* BackboneElement "Barlett Score" "Qualitative mikroskopische Beurteilung der Eignung von Sputumproben für die Kultur anhand des Verhältnisses von Entzündungs- zu Epithelzellen."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung der Untersuchung; hier fest: Barlett-Score (LOINC)."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "Score-Kategorie und daraus abgeleitete Eignung der Probe (LOINC)."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes Verfahren; hier fest: Mikroskopie (SNOMED CT)."
  * NugentScore 0..* BackboneElement "Nugent Score" "Gramfärbungs-basiertes semiquantitatives Punktesystem zur Beurteilung vaginaler Mikrobiotamuster bei bakterieller Vaginose."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung der Untersuchung; hier fest: Nugent-Score (LOINC)."
    * Ergebnis 0..1 Quantity "Ergebnis" "Punktwert des Nugent-Scores (dimensionslos)."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes Verfahren; hier fest: Mikroskopie (SNOMED CT)."
  * Keimzahl 0..* BackboneElement "Keimzahl" "Quantitative Bestimmung lebensfähiger Mikroorganismen in einer Probe als koloniebildende Einheiten pro Volumen oder Masse."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung der Keimzahlbestimmung (LOINC)."
    * Ergebnis 0..1 Quantity "Ergebnis" "Gemessene Keimzahl mit Einheit, z. B. KBE/mL (UCUM)."
    * Bewertung 0..1 CodeableConcept "Bewertung" "Semiquantitative Einordnung des Messwerts, z. B. geringes / mäßiges / reichliches Wachstum."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes Verfahren; hier fest: Auszählung (SNOMED CT)."
  * Empfindlichkeit 0..* BackboneElement "Empfindlichkeit" "Ergebnis der phänotypischen Resistenztestung eines Erregers gegenüber einer antimikrobiellen Substanz unter Bezug auf ein Normsystem."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Getestete antimikrobielle Substanz und Testverfahren (LOINC). Es werden bevorzugt Codes ohne präkoordinierte Probenart verwendet."
    * Ergebnis 0..1 Quantity "Ergebnis" "Gemessener Wert der Empfindlichkeitstestung, z. B. minimale Hemmkonzentration in mg/L oder Hemmhofdurchmesser in mm (UCUM)."
    * Bewertung 0..1 BackboneElement "Bewertung" "Kategoriale Bewertung des Messwerts (sensibel / intermediär / resistent)."
      * Kategorie 1..1 CodeableConcept "Kategorie" "Empfindlichkeitskategorie des getesteten Erregers."
      * Norm 1..1 CodeableConcept "Norm" "Normsystem einschließlich Version, auf dessen Grenzwerten die Kategorie beruht, z. B. EUCAST oder CLSI."

// Bestimmung
* Bestimmung 0..* BackboneElement "Bestimmung" "Identifikation bzw. Nachweis eines Mikroorganismus oder infektiösen Agens in einer Probe."
  * AllgemeineBestimmung 0..* BackboneElement "Allgemeine Bestimmung" "Identifikation eines Mikroorganismus oder infektiösen Agens ohne Einschränkung auf ein vordefiniertes Ziel."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung der Untersuchung; hier fest: Nachweis eines Mikroorganismus oder Agens in der Probe (LOINC)."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "Identifizierter Mikroorganismus bzw. identifiziertes Agens (SNOMED CT)."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes Nachweis- bzw. Identifikationsverfahren (SNOMED CT)."
  * SpezifischeBestimmung 0..* BackboneElement "Spezifische Bestimmung" "Qualitativer Nachweis eines vordefinierten mikrobiellen Ziels, kulturbasiert oder mittels molekularer, immunologischer oder biochemischer Verfahren."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung des gesuchten Ziels und des Testverfahrens (LOINC). Es werden bevorzugt Codes ohne präkoordinierte Probenart verwendet."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "Nachweisergebnis für das gesuchte Ziel (SNOMED CT)."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes Nachweisverfahren (SNOMED CT)."
  * CtWert 0..* BackboneElement "Ct-Wert" "Zyklusschwellenwert bei Nukleinsäurenachweisen, z. B. Echtzeit-PCR."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung des Ct-Werts für das jeweilige Ziel (LOINC). Es werden bevorzugt Codes ohne präkoordinierte Probenart verwendet."
    * Ergebnis 0..1 Quantity "Ergebnis" "Zyklusschwellenwert (dimensionslos)."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes Verfahren; hier fest: Echtzeit-PCR (SNOMED CT)."
    * AbgeleitetAus 0..* Reference(MII_LM_Mikrobio_Untersuchung) "Abgeleitet aus" "Untersuchung, aus der der Ct-Wert hervorgegangen ist, in der Regel die zugehörige spezifische Bestimmung."

// Weitere Eigenschaften
* WeitereEigenschaften 0..* BackboneElement "Weitere Eigenschaften" "Ergänzende Eigenschaften eines nachgewiesenen Erregers, insbesondere zu Virulenz und Resistenz."
  * Virulenzfaktor 0..* BackboneElement "Virulenzfaktor" "Qualitativer Nachweis oder Ausschluss von Virulenzdeterminanten in einer Probe."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung der untersuchten Virulenzdeterminante (LOINC)."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "Nachgewiesen oder nicht nachgewiesen (SNOMED CT)."
  * ResistenzmechanismenDeterminanten 0..* BackboneElement "Resistenzmechanismus" "Nachweis von Resistenzgenen oder Resistenzmutationen als Hinweis auf einen spezifischen Resistenzmechanismus."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung des untersuchten Resistenzgens bzw. Resistenzmechanismus (LOINC)."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "Nachgewiesen oder nicht nachgewiesen (SNOMED CT)."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes Nachweisverfahren (SNOMED CT)."
  * MRGNKlasse 0..* BackboneElement "MRGN Klasse" "Einstufung multiresistenter gramnegativer Erreger entsprechend der RKI-Kategorisierung."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung der Untersuchung; hier fest: MRGN-Klassifikation (LOINC)."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "MRGN-Klasse, z. B. 3MRGN oder 4MRGN (LOINC)."
  * VoraussichtlicheEmpfindlichkeit 0..* BackboneElement "Voraussichtliche Empfindlichkeit" "Aus genotypischen Nachweisen abgeleitete erwartete Empfindlichkeit oder Resistenz gegenüber antimikrobiellen Substanzen."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Betroffene antimikrobielle Substanz bzw. Substanzklasse (LOINC, genotypisch)."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "Erwartete Empfindlichkeit bzw. Resistenz."
  * MREStatus 0..* BackboneElement "MRE Status" "Aus den vorliegenden mikrobiologischen Befunden abgeleitete Aussage, ob ein Isolat als multiresistenter Erreger einzustufen ist."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung der Untersuchung; hier fest: MRE-Status (MII-CodeSystem)."
    * Ergebnis 0..1 CodeableConcept "Ergebnis" "Ja/Nein-Aussage zum MRE-Status (SNOMED CT)."
    * Grundlage 0..* BackboneElement "Grundlage" "Befunde, aus denen der MRE-Status abgeleitet wurde: Identifikation, Empfindlichkeit, Resistenzmechanismen und ggf. MRGN-Klassifikation."
  * Aviditaet 0..* BackboneElement "Aviditaet" "Beurteilung der Bindungsstärke von Antikörpern an ein spezifisches Antigen, typischerweise zur Unterscheidung frischer von zurückliegenden Infektionen."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung des Aviditätstests einschließlich Zielantigen (LOINC)."
    * Ergebnis 0..1 Quantity "Ergebnis" "Aviditätsindex in Prozent."
    * Bewertung 0..1 CodeableConcept "Bewertung" "Kategoriale Einordnung der Avidität, z. B. niedrig oder hoch."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes immunologisches Verfahren (SNOMED CT)."

// Quantitative Tests
* QuantitativeTests 0..* BackboneElement "Quantitative Tests" "Quantitative Messungen erregerspezifischer Analyte."
  * AntigenAntikoerperQuantitativ 0..* BackboneElement "Antigen Antikoerper Tests" "Quantitative Messung erregerspezifischer Antigene oder Antikörper mittels immunologischer Verfahren."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung des gemessenen Antigens bzw. Antikörpers (LOINC)."
    * Ergebnis 0..1 Quantity "Ergebnis" "Gemessene Konzentration bzw. Aktivität mit Einheit (UCUM)."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes immunologisches Verfahren (SNOMED CT)."
  * Titer 0..* BackboneElement "Titer" "Semiquantitative Messung aus seriellen Verdünnungsreihen, berichtet als Verhältnis, z. B. 1:160."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung des Titertests (LOINC)."
    * Ergebnis 0..1 Ratio "Ergebnis" "Titer als Verhältnis; der Zähler ist stets 1, der Nenner gibt die höchste noch reaktive Verdünnungsstufe an."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes Verfahren der Verdünnungsreihe (SNOMED CT)."
  * MolekularePathogenlast 0..* BackboneElement "Molekulare Pathogenlast" "Quantitative Messung der Nukleinsäurekonzentration eines Erregers, typischerweise als Konzentration pro Volumen."
    * Untersuchungscode 1..1 CodeableConcept "Untersuchungscode" "Kodierung der gemessenen Pathogenlast einschließlich Ziel (LOINC). Es werden bevorzugt Codes ohne präkoordinierte Probenart verwendet."
    * Ergebnis 0..1 Quantity "Ergebnis" "Gemessene Pathogenlast mit Einheit, z. B. Kopien/mL (UCUM)."
    * Untersuchungsmethode 0..1 CodeableConcept "Untersuchungsmethode" "Eingesetztes molekulares Verfahren (SNOMED CT)."
